@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.globl	gDebugPInfo
	.section .data,"aw"
	.align	2, 0
	.type	 gDebugPInfo,object
gDebugPInfo:
	.word	0x1
	.word	.LC0
	.word	.LC1
	.word	0x7
	.word	.LC2
	.word	.LC3
	.word	0x9
	.word	.LC4
	.word	.LC5
	.word	0x5
	.word	.LC6
	.word	.LC7
	.word	0x45
	.word	.LC8
	.word	.LC9
	.word	0x48
	.word	.LC10
	.word	.LC11
	.word	0x3d
	.word	.LC12
	.word	.LC13
	.word	0x19
	.word	.LC14
	.word	.LC15
	.word	0xd
	.word	.LC16
	.word	.LC17
	.word	0x3f
	.word	.LC18
	.word	.LC19
	.word	0x1b
	.word	.LC20
	.word	.LC21
	.word	0x25
	.word	.LC22
	.word	.LC23
	.word	0x4a
	.word	.LC24
	.word	.LC25
	.word	0x1f
	.word	.LC26
	.word	.LC27
	.word	0x1
	.word	.LC28
	.word	.LC1
	.word	0x5
	.word	.LC29
	.word	.LC7
	.word	0x5
	.word	.LC30
	.word	.LC7
	.word	0x47
	.word	.LC31
	.word	.LC32
	.word	0x44
	.word	.LC33
	.word	.LC34
	.word	0xf
	.word	.LC35
	.word	.LC36
	.word	0x4d
	.word	.LC37
	.word	.LC38
	.word	0x13
	.word	.LC39
	.word	.LC40
	.word	0x27
	.word	.LC41
	.word	.LC42
	.word	0x3e
	.word	.LC43
	.word	.LC44
	.word	0x4b
	.word	.LC45
	.word	.LC46
	.word	0x43
	.word	.LC47
	.word	.LC48
	.word	0x41
	.word	.LC49
	.word	.LC50
	.word	0x33
	.word	.LC51
	.word	.LC52
	.word	0x35
	.word	.LC53
	.word	.LC54
	.word	0x3b
	.word	.LC55
	.word	.LC56
	.word	0x2d
	.word	.LC57
	.word	.LC58
	.word	0x13
	.word	.LC59
	.word	.LC40
	.word	0x49
	.word	.LC60
	.word	.LC61
	.word	0x48
	.word	.LC62
	.word	.LC11
	.word	0x4f
	.word	.LC63
	.word	.LC64
	.word	0x7
	.word	.LC65
	.word	.LC3
	.word	0x21
	.word	.LC66
	.word	.LC67
	.word	0x29
	.word	.LC68
	.word	.LC69
	.word	0x23
	.word	.LC70
	.word	.LC71
	.word	0x2b
	.word	.LC72
	.word	.LC73
	.word	0x11
	.word	.LC74
	.word	.LC75
	.word	0xb
	.word	.LC76
	.word	.LC77
	.word	0x15
	.word	.LC78
	.word	.LC79
	.word	0x1d
	.word	.LC80
	.word	.LC81
	.word	0x41
	.word	.LC82
	.word	.LC50
	.word	0x41
	.word	.LC83
	.word	.LC50
	.word	0x41
	.word	.LC84
	.word	.LC50
	.word	0x41
	.word	.LC85
	.word	.LC50
	.word	0x41
	.word	.LC86
	.word	.LC50
	.word	0x41
	.word	.LC87
	.word	.LC50
	.word	0x41
	.word	.LC88
	.word	.LC50
	.word	0x41
	.word	.LC89
	.word	.LC50
	.word	0x41
	.word	.LC90
	.word	.LC50
	.word	0x41
	.word	.LC91
	.word	.LC50
	.word	0x41
	.word	.LC92
	.word	.LC50
	.word	0x41
	.word	.LC93
	.word	.LC50
	.word	0x41
	.word	.LC94
	.word	.LC50
	.word	0x41
	.word	.LC95
	.word	.LC50
	.word	0x51
	.word	.LC96
	.word	.LC97
	.word	0x31
	.word	.LC98
	.word	.LC99
	.word	0x31
	.word	.LC100
	.word	.LC99
	.word	0x51
	.word	.LC101
	.word	.LC97
	.word	0x51
	.word	.LC102
	.word	.LC97
	.word	0x4f
	.word	.LC103
	.word	.LC64
	.word	0x3b
	.word	.LC104
	.word	.LC56
	.word	0x7
	.word	.LC105
	.word	.LC3
	.word	0x23
	.word	.LC106
	.word	.LC71
	.word	0x29
	.word	.LC107
	.word	.LC69
	.word	0x23
	.word	.LC108
	.word	.LC71
	.word	0x9
	.word	.LC109
	.word	.LC5
	.word	0x41
	.word	.LC110
	.word	.LC50
	.word	0x41
	.word	.LC111
	.word	.LC50
	.word	0x53
	.word	.LC112
	.word	.LC113
	.word	0x9
	.word	.LC114
	.word	.LC5
	.word	0x2d
	.word	.LC115
	.word	.LC58
	.word	0x5
	.word	.LC116
	.word	.LC7
	.word	0xb
	.word	.LC117
	.word	.LC77
	.word	0x40
	.word	.LC118
	.word	.LC119
	.word	0x27
	.word	.LC120
	.word	.LC42
	.word	0x5e
	.word	.LC121
	.word	.LC122
	.word	0x35
	.word	.LC123
	.word	.LC54
	.word	0x15
	.word	.LC124
	.word	.LC79
	.word	0x11
	.word	.LC125
	.word	.LC75
	.word	0x27
	.word	.LC126
	.word	.LC42
	.word	0x41
	.word	.LC127
	.word	.LC50
	.word	0x61
	.word	.LC128
	.word	.LC129
	.word	0x2b
	.word	.LC130
	.word	.LC73
	.word	0x41
	.word	.LC131
	.word	.LC50
	.word	0x41
	.word	.LC132
	.word	.LC50
	.word	0x40
	.word	.LC133
	.word	.LC119
	.word	0x1d
	.word	.LC134
	.word	.LC81
	.word	0x5a
	.word	.LC135
	.word	.LC136
	.word	0x56
	.word	.LC137
	.word	.LC138
	.word	0x64
	.word	.LC139
	.word	.LC140
	.word	0x53
	.word	.LC141
	.word	.LC113
	.word	0x41
	.word	.LC142
	.word	.LC50
	.word	0x41
	.word	.LC143
	.word	.LC50
	.word	0x41
	.word	.LC144
	.word	.LC50
	.word	0x41
	.word	.LC145
	.word	.LC50
	.word	0xd
	.word	.LC146
	.word	.LC17
	.word	0x41
	.word	.LC147
	.word	.LC50
	.word	0x41
	.word	.LC148
	.word	.LC50
	.word	0x41
	.word	.LC149
	.word	.LC50
	.word	0x3f
	.word	.LC150
	.word	.LC19
	.word	0x21
	.word	.LC151
	.word	.LC67
	.word	0xf
	.word	.LC152
	.word	.LC36
	.word	0xb
	.word	.LC153
	.word	.LC77
	.word	0x4f
	.word	.LC154
	.word	.LC64
	.word	0x7
	.word	.LC155
	.word	.LC3
	.word	0x41
	.word	.LC156
	.word	.LC50
	.word	0x41
	.word	.LC157
	.word	.LC50
	.word	0x41
	.word	.LC158
	.word	.LC50
	.word	0x41
	.word	.LC159
	.word	.LC50
	.word	0x41
	.word	.LC160
	.word	.LC50
	.word	0x41
	.word	.LC161
	.word	.LC50
	.word	0x41
	.word	.LC162
	.word	.LC50
	.word	0x41
	.word	.LC163
	.word	.LC50
	.word	0x41
	.word	.LC164
	.word	.LC50
	.word	0x41
	.word	.LC165
	.word	.LC50
	.word	0x41
	.word	.LC166
	.word	.LC50
	.word	0x41
	.word	.LC167
	.word	.LC50
	.word	0x41
	.word	.LC168
	.word	.LC50
	.word	0x41
	.word	.LC169
	.word	.LC50
	.word	0x41
	.word	.LC170
	.word	.LC50
	.word	0x41
	.word	.LC171
	.word	.LC50
	.word	0x41
	.word	.LC172
	.word	.LC50
	.word	0x5
	.word	.LC173
	.word	.LC7
	.word	0x3f
	.word	.LC174
	.word	.LC19
	.word	0x19
	.word	.LC175
	.word	.LC15
	.word	0x3f
	.word	.LC176
	.word	.LC19
	.word	0x4e
	.word	.LC177
	.word	.LC178
	.word	0x9
	.word	.LC179
	.word	.LC5
	.word	0x5
	.word	.LC180
	.word	.LC7
	.word	0x13
	.word	.LC181
	.word	.LC40
	.word	0xf
	.word	.LC182
	.word	.LC36
	.word	0xd
	.word	.LC183
	.word	.LC17
	.word	0x25
	.word	.LC184
	.word	.LC23
	.word	0x44
	.word	.LC185
	.word	.LC34
	.word	0x2d
	.word	.LC186
	.word	.LC58
	.word	0x4b
	.word	.LC187
	.word	.LC46
	.word	0x9
	.word	.LC188
	.word	.LC5
	.word	0x41
	.word	.LC189
	.word	.LC50
	.word	0x5
	.word	.LC190
	.word	.LC7
	.word	0x2d
	.word	.LC191
	.word	.LC58
	.word	0x25
	.word	.LC192
	.word	.LC23
	.word	0x41
	.word	.LC193
	.word	.LC50
	.word	0x41
	.word	.LC194
	.word	.LC50
	.word	0x41
	.word	.LC195
	.word	.LC50
	.word	0x41
	.word	.LC196
	.word	.LC50
	.word	0x41
	.word	.LC197
	.word	.LC50
	.word	0x41
	.word	.LC198
	.word	.LC50
	.word	0x41
	.word	.LC199
	.word	.LC50
	.word	0x41
	.word	.LC200
	.word	.LC50
	.word	0x41
	.word	.LC201
	.word	.LC50
	.word	0x41
	.word	.LC202
	.word	.LC50
	.word	0x41
	.word	.LC203
	.word	.LC50
	.word	0x41
	.word	.LC204
	.word	.LC50
	.word	0x41
	.word	.LC205
	.word	.LC50
	.word	0x41
	.word	.LC206
	.word	.LC50
	.word	0x41
	.word	.LC207
	.word	.LC50
	.word	0x41
	.word	.LC208
	.word	.LC50
	.word	0x41
	.word	.LC209
	.word	.LC50
	.word	0x41
	.word	.LC210
	.word	.LC50
	.word	0x41
	.word	.LC211
	.word	.LC50
	.word	0x41
	.word	.LC212
	.word	.LC50
	.word	0x41
	.word	.LC213
	.word	.LC50
	.word	0xf
	.word	.LC36
	.word	.LC36
	.word	0xf
	.word	.LC214
	.word	.LC36
	.word	0xf
	.word	.LC215
	.word	.LC36
	.word	0x52
	.word	.LC216
	.word	.LC217
	.word	0x53
	.word	.LC113
	.word	.LC113
	.word	0x54
	.word	.LC218
	.word	.LC218
	.word	0x55
	.word	.LC219
	.word	.LC219
	.word	0x56
	.word	.LC138
	.word	.LC138
	.word	0x57
	.word	.LC220
	.word	.LC220
	.word	0x58
	.word	.LC221
	.word	.LC221
	.word	0x59
	.word	.LC222
	.word	.LC222
	.word	0x5a
	.word	.LC136
	.word	.LC136
	.word	0x5b
	.word	.LC223
	.word	.LC223
	.word	0x5c
	.word	.LC224
	.word	.LC224
	.word	0x5d
	.word	.LC225
	.word	.LC225
	.word	0x5e
	.word	.LC122
	.word	.LC122
	.word	0x5f
	.word	.LC226
	.word	.LC226
	.word	0x60
	.word	.LC227
	.word	.LC227
	.word	0x61
	.word	.LC129
	.word	.LC129
	.word	0x62
	.word	.LC228
	.word	.LC228
	.word	0x63
	.word	.LC229
	.word	.LC229
	.word	0x64
	.word	.LC140
	.word	.LC140
	.word	0x65
	.word	.LC230
	.word	.LC230
	.word	0x66
	.word	.LC231
	.word	.LC231
	.word	0x41
	.word	.LC232
	.word	.LC50
	.word	0x13
	.word	.LC233
	.word	.LC40
	.word	0x5
	.word	.LC234
	.word	.LC7
	.word	0x41
	.word	.LC235
	.word	.LC50
	.word	0x41
	.word	.LC236
	.word	.LC50
	.word	0x41
	.word	.LC237
	.word	.LC50
	.word	0x27
	.word	.LC238
	.word	.LC42
	.word	0x41
	.word	.LC239
	.word	.LC50
	.word	0x73
	.word	.LC240
	.word	.LC241
	.word	0x7a
	.word	.LC242
	.word	.LC243
	.word	0x2b
	.word	.LC244
	.word	.LC73
	.word	0x2f
	.word	.LC245
	.word	.LC246
	.word	0x73
	.word	.LC247
	.word	.LC241
	.word	0x48
	.word	.LC248
	.word	.LC11
	.word	0x9
	.word	.LC249
	.word	.LC5
	.word	0x9
	.word	.LC250
	.word	.LC5
	.word	0x41
	.word	.LC251
	.word	.LC50
	.word	0x41
	.word	.LC252
	.word	.LC50
	.word	0x41
	.word	.LC253
	.word	.LC50
	.word	0x41
	.word	.LC254
	.word	.LC50
	.word	0x41
	.word	.LC255
	.word	.LC50
	.word	0x41
	.word	.LC256
	.word	.LC50
	.word	0x41
	.word	.LC257
	.word	.LC50
	.word	0x41
	.word	.LC258
	.word	.LC50
	.word	0x41
	.word	.LC259
	.word	.LC50
	.word	0x41
	.word	.LC260
	.word	.LC50
	.word	0x41
	.word	.LC261
	.word	.LC50
	.word	0x41
	.word	.LC262
	.word	.LC50
	.word	0x41
	.word	.LC263
	.word	.LC50
	.word	0x41
	.word	.LC264
	.word	.LC50
	.word	0x41
	.word	.LC265
	.word	.LC50
	.word	0x41
	.word	.LC266
	.word	.LC50
	.word	0x41
	.word	.LC267
	.word	.LC50
	.word	0x41
	.word	.LC268
	.word	.LC50
	.word	0x41
	.word	.LC269
	.word	.LC50
	.word	0x41
	.word	.LC270
	.word	.LC50
	.word	0x41
	.word	.LC271
	.word	.LC50
	.word	0x41
	.word	.LC272
	.word	.LC50
	.word	0x41
	.word	.LC273
	.word	.LC50
	.word	0x41
	.word	.LC274
	.word	.LC50
	.word	0x41
	.word	.LC275
	.word	.LC50
	.word	0x41
	.word	.LC276
	.word	.LC50
	.word	0x41
	.word	.LC277
	.word	.LC50
	.word	0x41
	.word	.LC278
	.word	.LC50
	.word	0x41
	.word	.LC279
	.word	.LC50
	.word	0x41
	.word	.LC280
	.word	.LC50
	.word	0x41
	.word	.LC281
	.word	.LC50
	.word	0x41
	.word	.LC282
	.word	.LC50
	.word	0x41
	.word	.LC283
	.word	.LC50
	.word	0x41
	.word	.LC284
	.word	.LC50
	.word	0x41
	.word	.LC285
	.word	.LC50
	.word	0x41
	.word	.LC286
	.word	.LC50
	.word	0x41
	.word	.LC287
	.word	.LC50
	.word	0x6d
	.word	.LC288
	.word	.LC289
	.word	0x6e
	.word	.LC290
	.word	.LC291
	.word	0x6f
	.word	.LC292
	.word	.LC293
	.word	0x70
	.word	.LC294
	.word	.LC295
	.word	0x6d
	.word	.LC289
	.word	.LC289
	.word	0x6e
	.word	.LC291
	.word	.LC291
	.word	0x71
	.word	.LC296
	.word	.LC297
	.word	0x71
	.word	.LC298
	.word	.LC297
	.word	0x71
	.word	.LC299
	.word	.LC297
	.word	0x41
	.word	.LC300
	.word	.LC50
	.word	0x41
	.word	.LC301
	.word	.LC50
	.word	0x41
	.word	.LC302
	.word	.LC50
	.word	0x41
	.word	.LC303
	.word	.LC50
	.section .rodata
	.align	2, 0
.LC303:
	.ascii	"FE3_DUMMY\000"
	.align	2, 0
.LC302:
	.ascii	"LOGBREAK\000"
	.align	2, 0
.LC301:
	.ascii	"WALLBREAK\000"
	.align	2, 0
.LC300:
	.ascii	"DUELTARGET\000"
	.align	2, 0
.LC299:
	.ascii	"NOTATTACK\000"
	.align	2, 0
.LC298:
	.ascii	"CITIZEN_F\000"
	.align	2, 0
.LC297:
	.ascii	"CIVILIAN\000"
	.align	2, 0
.LC296:
	.ascii	"CITIZEN\000"
	.align	2, 0
.LC295:
	.ascii	"KOIDO_F\000"
	.align	2, 0
.LC294:
	.ascii	"CITIZEN2_F\000"
	.align	2, 0
.LC293:
	.ascii	"KOIDO_M\000"
	.align	2, 0
.LC292:
	.ascii	"CITIZEN2\000"
	.align	2, 0
.LC291:
	.ascii	"CHILD_F\000"
	.align	2, 0
.LC290:
	.ascii	"CHILD2_F\000"
	.align	2, 0
.LC289:
	.ascii	"CHILD\000"
	.align	2, 0
.LC288:
	.ascii	"CHILD2\000"
	.align	2, 0
.LC287:
	.ascii	"EMPTY_251\000"
	.align	2, 0
.LC286:
	.ascii	"EMPTY_250\000"
	.align	2, 0
.LC285:
	.ascii	"EMPTY_249\000"
	.align	2, 0
.LC284:
	.ascii	"EMPTY_248\000"
	.align	2, 0
.LC283:
	.ascii	"EMPTY_247\000"
	.align	2, 0
.LC282:
	.ascii	"EMPTY_246\000"
	.align	2, 0
.LC281:
	.ascii	"EMPTY_245\000"
	.align	2, 0
.LC280:
	.ascii	"EMPTY_244\000"
	.align	2, 0
.LC279:
	.ascii	"EMPTY_243\000"
	.align	2, 0
.LC278:
	.ascii	"EMPTY_242\000"
	.align	2, 0
.LC277:
	.ascii	"EMPTY_241\000"
	.align	2, 0
.LC276:
	.ascii	"EMPTY_240\000"
	.align	2, 0
.LC275:
	.ascii	"EMPTY_239\000"
	.align	2, 0
.LC274:
	.ascii	"EMPTY_238\000"
	.align	2, 0
.LC273:
	.ascii	"EMPTY_237\000"
	.align	2, 0
.LC272:
	.ascii	"EMPTY_236\000"
	.align	2, 0
.LC271:
	.ascii	"EMPTY_235\000"
	.align	2, 0
.LC270:
	.ascii	"EMPTY_234\000"
	.align	2, 0
.LC269:
	.ascii	"EMPTY_233\000"
	.align	2, 0
.LC268:
	.ascii	"EMPTY_232\000"
	.align	2, 0
.LC267:
	.ascii	"EMPTY_231\000"
	.align	2, 0
.LC266:
	.ascii	"EMPTY_230\000"
	.align	2, 0
.LC265:
	.ascii	"EMPTY_229\000"
	.align	2, 0
.LC264:
	.ascii	"EMPTY_228\000"
	.align	2, 0
.LC263:
	.ascii	"EMPTY_227\000"
	.align	2, 0
.LC262:
	.ascii	"EMPTY_226\000"
	.align	2, 0
.LC261:
	.ascii	"EMPTY_225\000"
	.align	2, 0
.LC260:
	.ascii	"EMPTY_224\000"
	.align	2, 0
.LC259:
	.ascii	"EMPTY_223\000"
	.align	2, 0
.LC258:
	.ascii	"EMPTY_222\000"
	.align	2, 0
.LC257:
	.ascii	"EMPTY_221\000"
	.align	2, 0
.LC256:
	.ascii	"EMPTY_220\000"
	.align	2, 0
.LC255:
	.ascii	"EMPTY_219\000"
	.align	2, 0
.LC254:
	.ascii	"EMPTY_218\000"
	.align	2, 0
.LC253:
	.ascii	"EMPTY_217\000"
	.align	2, 0
.LC252:
	.ascii	"EMPTY_216\000"
	.align	2, 0
.LC251:
	.ascii	"EMPTY_215\000"
	.align	2, 0
.LC250:
	.ascii	"ROSTON_SOLDIER2\000"
	.align	2, 0
.LC249:
	.ascii	"ROSTON_SOLDIER\000"
	.align	2, 0
.LC248:
	.ascii	"MESSENGER1\000"
	.align	2, 0
.LC247:
	.ascii	"ISHUMARE\000"
	.align	2, 0
.LC246:
	.ascii	"DRUID\000"
	.align	2, 0
.LC245:
	.ascii	"DARA\000"
	.align	2, 0
.LC244:
	.ascii	"KLIMT\000"
	.align	2, 0
.LC243:
	.ascii	"POPE\000"
	.align	2, 0
.LC242:
	.ascii	"MANSELL\000"
	.align	2, 0
.LC241:
	.ascii	"PEER\000"
	.align	2, 0
.LC240:
	.ascii	"HAYDEN\000"
	.align	2, 0
.LC239:
	.ascii	"EMPTY_189\000"
	.align	2, 0
.LC238:
	.ascii	"FADO\000"
	.align	2, 0
.LC237:
	.ascii	"EMPTY_187\000"
	.align	2, 0
.LC236:
	.ascii	"EMPTY_186\000"
	.align	2, 0
.LC235:
	.ascii	"EMPTY_185\000"
	.align	2, 0
.LC234:
	.ascii	"FRERIA_SOCIALKNIGHT\000"
	.align	2, 0
.LC233:
	.ascii	"FRERIA_SWORDFIGHTER\000"
	.align	2, 0
.LC232:
	.ascii	"EMPTY_182\000"
	.align	2, 0
.LC231:
	.ascii	"FODETH\000"
	.align	2, 0
.LC230:
	.ascii	"DRAGONZOMBIE\000"
	.align	2, 0
.LC229:
	.ascii	"GARGOYLE\000"
	.align	2, 0
.LC228:
	.ascii	"GORGONEGG\000"
	.align	2, 0
.LC227:
	.ascii	"DETHBIGL\000"
	.align	2, 0
.LC226:
	.ascii	"BIGL\000"
	.align	2, 0
.LC225:
	.ascii	"TARVOS\000"
	.align	2, 0
.LC224:
	.ascii	"CERBERUS\000"
	.align	2, 0
.LC223:
	.ascii	"MAUTHEDOOG\000"
	.align	2, 0
.LC222:
	.ascii	"DETHBAEL\000"
	.align	2, 0
.LC221:
	.ascii	"BAEL\000"
	.align	2, 0
.LC220:
	.ascii	"HELLSKELETON_A\000"
	.align	2, 0
.LC219:
	.ascii	"SKELETON_A\000"
	.align	2, 0
.LC218:
	.ascii	"SKELETON_S\000"
	.align	2, 0
.LC217:
	.ascii	"ZOMBIE\000"
	.align	2, 0
.LC216:
	.ascii	"ZONBIE\000"
	.align	2, 0
.LC215:
	.ascii	"CARCINO_REMNANTS\000"
	.align	2, 0
.LC214:
	.ascii	"CARCINO_MERCENARY\000"
	.align	2, 0
.LC213:
	.ascii	"EMPTY_159\000"
	.align	2, 0
.LC212:
	.ascii	"EMPTY_158\000"
	.align	2, 0
.LC211:
	.ascii	"EMPTY_157\000"
	.align	2, 0
.LC210:
	.ascii	"EMPTY_156\000"
	.align	2, 0
.LC209:
	.ascii	"EMPTY_155\000"
	.align	2, 0
.LC208:
	.ascii	"EMPTY_154\000"
	.align	2, 0
.LC207:
	.ascii	"EMPTY_153\000"
	.align	2, 0
.LC206:
	.ascii	"EMPTY_152\000"
	.align	2, 0
.LC205:
	.ascii	"EMPTY_151\000"
	.align	2, 0
.LC204:
	.ascii	"EMPTY_150\000"
	.align	2, 0
.LC203:
	.ascii	"EMPTY_149\000"
	.align	2, 0
.LC202:
	.ascii	"EMPTY_148\000"
	.align	2, 0
.LC201:
	.ascii	"EMPTY_147\000"
	.align	2, 0
.LC200:
	.ascii	"EMPTY_146\000"
	.align	2, 0
.LC199:
	.ascii	"EMPTY_145\000"
	.align	2, 0
.LC198:
	.ascii	"EMPTY_144\000"
	.align	2, 0
.LC197:
	.ascii	"EMPTY_143\000"
	.align	2, 0
.LC196:
	.ascii	"EMPTY_142\000"
	.align	2, 0
.LC195:
	.ascii	"EMPTY_141\000"
	.align	2, 0
.LC194:
	.ascii	"EMPTY_140\000"
	.align	2, 0
.LC193:
	.ascii	"EMPTY_139\000"
	.align	2, 0
.LC192:
	.ascii	"GRAD_REMNANTS4\000"
	.align	2, 0
.LC191:
	.ascii	"GRAD_REMNANTS3\000"
	.align	2, 0
.LC190:
	.ascii	"GRAD_REMNANTS2\000"
	.align	2, 0
.LC189:
	.ascii	"BANDIT_BAZBA\000"
	.align	2, 0
.LC188:
	.ascii	"GRAD_REMNANTS\000"
	.align	2, 0
.LC187:
	.ascii	"GRAD_10\000"
	.align	2, 0
.LC186:
	.ascii	"GRAD_09\000"
	.align	2, 0
.LC185:
	.ascii	"GRAD_08\000"
	.align	2, 0
.LC184:
	.ascii	"GRAD_07\000"
	.align	2, 0
.LC183:
	.ascii	"GRAD_06\000"
	.align	2, 0
.LC182:
	.ascii	"GRAD_05\000"
	.align	2, 0
.LC181:
	.ascii	"GRAD_04\000"
	.align	2, 0
.LC180:
	.ascii	"GRAD_03\000"
	.align	2, 0
.LC179:
	.ascii	"GRAD_02\000"
	.align	2, 0
.LC178:
	.ascii	"SOLDIER\000"
	.align	2, 0
.LC177:
	.ascii	"GRAD_01\000"
	.align	2, 0
.LC176:
	.ascii	"GRAD_FIGHTER2\000"
	.align	2, 0
.LC175:
	.ascii	"GRAD_ARCHER\000"
	.align	2, 0
.LC174:
	.ascii	"GRAD_FIGHTER\000"
	.align	2, 0
.LC173:
	.ascii	"GRAD_L06\000"
	.align	2, 0
.LC172:
	.ascii	"EMPTY_121\000"
	.align	2, 0
.LC171:
	.ascii	"EMPTY_120\000"
	.align	2, 0
.LC170:
	.ascii	"EMPTY_119\000"
	.align	2, 0
.LC169:
	.ascii	"EMPTY_118\000"
	.align	2, 0
.LC168:
	.ascii	"EMPTY_117\000"
	.align	2, 0
.LC167:
	.ascii	"EMPTY_116\000"
	.align	2, 0
.LC166:
	.ascii	"EMPTY_115\000"
	.align	2, 0
.LC165:
	.ascii	"EMPTY_114\000"
	.align	2, 0
.LC164:
	.ascii	"EMPTY_113\000"
	.align	2, 0
.LC163:
	.ascii	"EMPTY_112\000"
	.align	2, 0
.LC162:
	.ascii	"EMPTY_111\000"
	.align	2, 0
.LC161:
	.ascii	"EMPTY_110\000"
	.align	2, 0
.LC160:
	.ascii	"EMPTY_109\000"
	.align	2, 0
.LC159:
	.ascii	"EMPTY_108\000"
	.align	2, 0
.LC158:
	.ascii	"EMPTY_107\000"
	.align	2, 0
.LC157:
	.ascii	"EMPTY_106\000"
	.align	2, 0
.LC156:
	.ascii	"EMPTY_105\000"
	.align	2, 0
.LC155:
	.ascii	"OLSSON2\000"
	.align	2, 0
.LC154:
	.ascii	"LYON2\000"
	.align	2, 0
.LC153:
	.ascii	"VIGARD\000"
	.align	2, 0
.LC152:
	.ascii	"ZONTA\000"
	.align	2, 0
.LC151:
	.ascii	"GLEN\000"
	.align	2, 0
.LC150:
	.ascii	"ONEILL\000"
	.align	2, 0
.LC149:
	.ascii	"BANDIT2\000"
	.align	2, 0
.LC148:
	.ascii	"BANDIT1\000"
	.align	2, 0
.LC147:
	.ascii	"BANDIT3\000"
	.align	2, 0
.LC146:
	.ascii	"TREASUREHUNTER\000"
	.align	2, 0
.LC145:
	.ascii	"EMPTY_094\000"
	.align	2, 0
.LC144:
	.ascii	"EMPTY_093\000"
	.align	2, 0
.LC143:
	.ascii	"EMPTY_092\000"
	.align	2, 0
.LC142:
	.ascii	"EMPTY_091\000"
	.align	2, 0
.LC141:
	.ascii	"MOSTER_BOSS\000"
	.align	2, 0
.LC140:
	.ascii	"DETHGARGOYLE\000"
	.align	2, 0
.LC139:
	.ascii	"MONSTER_i10x\000"
	.align	2, 0
.LC138:
	.ascii	"HELLSKELETON_S\000"
	.align	2, 0
.LC137:
	.ascii	"MONSTER_E10x\000"
	.align	2, 0
.LC136:
	.ascii	"CYCLOPS\000"
	.align	2, 0
.LC135:
	.ascii	"CYCLOPS_i11\000"
	.align	2, 0
.LC134:
	.ascii	"BERNA\000"
	.align	2, 0
.LC133:
	.ascii	"GEB\000"
	.align	2, 0
.LC132:
	.ascii	"EMPTY_084\000"
	.align	2, 0
.LC131:
	.ascii	"EMPTY_083\000"
	.align	2, 0
.LC130:
	.ascii	"IRV\000"
	.align	2, 0
.LC129:
	.ascii	"GORGON\000"
	.align	2, 0
.LC128:
	.ascii	"DEMI\000"
	.align	2, 0
.LC127:
	.ascii	"EMPTY_080\000"
	.align	2, 0
.LC126:
	.ascii	"PABLO_E12\000"
	.align	2, 0
.LC125:
	.ascii	"CETHELREDA\000"
	.align	2, 0
.LC124:
	.ascii	"CARLYLE\000"
	.align	2, 0
.LC123:
	.ascii	"AIAS\000"
	.align	2, 0
.LC122:
	.ascii	"MACDAIRE\000"
	.align	2, 0
.LC121:
	.ascii	"MACDAIRE_e11\000"
	.align	2, 0
.LC120:
	.ascii	"PABLO\000"
	.align	2, 0
.LC119:
	.ascii	"WARRIOR\000"
	.align	2, 0
.LC118:
	.ascii	"BINKS\000"
	.align	2, 0
.LC117:
	.ascii	"TIRADO\000"
	.align	2, 0
.LC116:
	.ascii	"MURRAY\000"
	.align	2, 0
.LC115:
	.ascii	"NOVELA\000"
	.align	2, 0
.LC114:
	.ascii	"SAAR\000"
	.align	2, 0
.LC113:
	.ascii	"MUMMY\000"
	.align	2, 0
.LC112:
	.ascii	"MUMMY_L04\000"
	.align	2, 0
.LC111:
	.ascii	"BAZBA\000"
	.align	2, 0
.LC110:
	.ascii	"BON\000"
	.align	2, 0
.LC109:
	.ascii	"BREGUET\000"
	.align	2, 0
.LC108:
	.ascii	"WALTER_L00\000"
	.align	2, 0
.LC107:
	.ascii	"CELINA\000"
	.align	2, 0
.LC106:
	.ascii	"WALTER\000"
	.align	2, 0
.LC105:
	.ascii	"OLSSON\000"
	.align	2, 0
.LC104:
	.ascii	"MORVA\000"
	.align	2, 0
.LC103:
	.ascii	"LYON\000"
	.align	2, 0
.LC102:
	.ascii	"PHANTOM_FIGHTER01\000"
	.align	2, 0
.LC101:
	.ascii	"PHANTOM_FIGHTER02\000"
	.align	2, 0
.LC100:
	.ascii	"EMPTY_057\000"
	.align	2, 0
.LC99:
	.ascii	"SUMMONER\000"
	.align	2, 0
.LC98:
	.ascii	"EMPTY_056\000"
	.align	2, 0
.LC97:
	.ascii	"PHANTOM\000"
	.align	2, 0
.LC96:
	.ascii	"PHANTOM_FIGHTER03\000"
	.align	2, 0
.LC95:
	.ascii	"EMPTY_054\000"
	.align	2, 0
.LC94:
	.ascii	"EMPTY_053\000"
	.align	2, 0
.LC93:
	.ascii	"EMPTY_052\000"
	.align	2, 0
.LC92:
	.ascii	"EMPTY_051\000"
	.align	2, 0
.LC91:
	.ascii	"EMPTY_050\000"
	.align	2, 0
.LC90:
	.ascii	"EMPTY_049\000"
	.align	2, 0
.LC89:
	.ascii	"EMPTY_048\000"
	.align	2, 0
.LC88:
	.ascii	"EMPTY_047\000"
	.align	2, 0
.LC87:
	.ascii	"EMPTY_046\000"
	.align	2, 0
.LC86:
	.ascii	"EMPTY_045\000"
	.align	2, 0
.LC85:
	.ascii	"EMPTY_044\000"
	.align	2, 0
.LC84:
	.ascii	"EMPTY_043\000"
	.align	2, 0
.LC83:
	.ascii	"EMPTY_042\000"
	.align	2, 0
.LC82:
	.ascii	"EMPTY_041\000"
	.align	2, 0
.LC81:
	.ascii	"FORRESTKNIGHT\000"
	.align	2, 0
.LC80:
	.ascii	"HAYDEN_C\000"
	.align	2, 0
.LC79:
	.ascii	"SWORDMASTER\000"
	.align	2, 0
.LC78:
	.ascii	"ISHUMARE_C\000"
	.align	2, 0
.LC77:
	.ascii	"GENERAL\000"
	.align	2, 0
.LC76:
	.ascii	"FADO_C\000"
	.align	2, 0
.LC75:
	.ascii	"HERO\000"
	.align	2, 0
.LC74:
	.ascii	"CETHELREDA_C\000"
	.align	2, 0
.LC73:
	.ascii	"BISHOP\000"
	.align	2, 0
.LC72:
	.ascii	"IRV_C\000"
	.align	2, 0
.LC71:
	.ascii	"WYVERNKNIGHT\000"
	.align	2, 0
.LC70:
	.ascii	"WALTER_C\000"
	.align	2, 0
.LC69:
	.ascii	"MAGEKNIGHT\000"
	.align	2, 0
.LC68:
	.ascii	"CELINA_C\000"
	.align	2, 0
.LC67:
	.ascii	"DRAGONMASTER\000"
	.align	2, 0
.LC66:
	.ascii	"GLEN_C\000"
	.align	2, 0
.LC65:
	.ascii	"OLSSON_C\000"
	.align	2, 0
.LC64:
	.ascii	"NECROMANCER\000"
	.align	2, 0
.LC63:
	.ascii	"LYON_C\000"
	.align	2, 0
.LC62:
	.ascii	"TURNER\000"
	.align	2, 0
.LC61:
	.ascii	"FALCONKNIGHT_F\000"
	.align	2, 0
.LC60:
	.ascii	"SYRENE\000"
	.align	2, 0
.LC59:
	.ascii	"JHOSUA\000"
	.align	2, 0
.LC58:
	.ascii	"SHAMAN\000"
	.align	2, 0
.LC57:
	.ascii	"KNOLL\000"
	.align	2, 0
.LC56:
	.ascii	"MAMKUTE\000"
	.align	2, 0
.LC55:
	.ascii	"MYRRH\000"
	.align	2, 0
.LC54:
	.ascii	"GREATKNIGHT\000"
	.align	2, 0
.LC53:
	.ascii	"DUSSEL\000"
	.align	2, 0
.LC52:
	.ascii	"ROGUE\000"
	.align	2, 0
.LC51:
	.ascii	"RENNAC\000"
	.align	2, 0
.LC50:
	.ascii	"MOUNTAINTHIEF\000"
	.align	2, 0
.LC49:
	.ascii	"EMPTY_023\000"
	.align	2, 0
.LC48:
	.ascii	"BERSERKER\000"
	.align	2, 0
.LC47:
	.ascii	"DOZZLA\000"
	.align	2, 0
.LC46:
	.ascii	"TROUBADOUR_F\000"
	.align	2, 0
.LC45:
	.ascii	"LARCHEL\000"
	.align	2, 0
.LC44:
	.ascii	"PROBATION_MAGE\000"
	.align	2, 0
.LC43:
	.ascii	"EWAN\000"
	.align	2, 0
.LC42:
	.ascii	"SAGE\000"
	.align	2, 0
.LC41:
	.ascii	"SALEH\000"
	.align	2, 0
.LC40:
	.ascii	"SWORDFIGHTER\000"
	.align	2, 0
.LC39:
	.ascii	"MARICA\000"
	.align	2, 0
.LC38:
	.ascii	"DANCER_F\000"
	.align	2, 0
.LC37:
	.ascii	"TETHYS\000"
	.align	2, 0
.LC36:
	.ascii	"MERCENARY\000"
	.align	2, 0
.LC35:
	.ascii	"XYST\000"
	.align	2, 0
.LC34:
	.ascii	"MONK\000"
	.align	2, 0
.LC33:
	.ascii	"ASSERAY\000"
	.align	2, 0
.LC32:
	.ascii	"PROBATION_FLY_F\000"
	.align	2, 0
.LC31:
	.ascii	"AMELIA\000"
	.align	2, 0
.LC30:
	.ascii	"KYLE\000"
	.align	2, 0
.LC29:
	.ascii	"FORDE\000"
	.align	2, 0
.LC28:
	.ascii	"IRZARK\000"
	.align	2, 0
.LC27:
	.ascii	"DRAGONKNIGHT\000"
	.align	2, 0
.LC26:
	.ascii	"CUGAR\000"
	.align	2, 0
.LC25:
	.ascii	"PRIEST_F\000"
	.align	2, 0
.LC24:
	.ascii	"NATASHA\000"
	.align	2, 0
.LC23:
	.ascii	"MAGE\000"
	.align	2, 0
.LC22:
	.ascii	"LUTE\000"
	.align	2, 0
.LC21:
	.ascii	"SNIPER\000"
	.align	2, 0
.LC20:
	.ascii	"HEANIUS\000"
	.align	2, 0
.LC19:
	.ascii	"FIGHTER\000"
	.align	2, 0
.LC18:
	.ascii	"BORBA\000"
	.align	2, 0
.LC17:
	.ascii	"THIEF\000"
	.align	2, 0
.LC16:
	.ascii	"COMA\000"
	.align	2, 0
.LC15:
	.ascii	"ARCHER\000"
	.align	2, 0
.LC14:
	.ascii	"MARY\000"
	.align	2, 0
.LC13:
	.ascii	"PROBATION_SOLDIER\000"
	.align	2, 0
.LC12:
	.ascii	"ROSS\000"
	.align	2, 0
.LC11:
	.ascii	"PEGASUSKNIGHT_F\000"
	.align	2, 0
.LC10:
	.ascii	"VANESSA\000"
	.align	2, 0
.LC9:
	.ascii	"PRIEST\000"
	.align	2, 0
.LC8:
	.ascii	"MULDER\000"
	.align	2, 0
.LC7:
	.ascii	"SOCIALKNIGHT\000"
	.align	2, 0
.LC6:
	.ascii	"FRANZ\000"
	.align	2, 0
.LC5:
	.ascii	"ARMORKNIGHT\000"
	.align	2, 0
.LC4:
	.ascii	"GILLIAM\000"
	.align	2, 0
.LC3:
	.ascii	"PALADIN\000"
	.align	2, 0
.LC2:
	.ascii	"SETH\000"
	.align	2, 0
.LC1:
	.ascii	"LORD\000"
	.align	2, 0
.LC0:
	.ascii	"EIRIKR\000"
	.size	 gDebugPInfo,3072

	.section	.text
.Letext0:

	.section	.debug_abbrev
	.byte	0x1
	.byte	0x11
	.byte	0x1
	.byte	0x3
	.byte	0x8
	.byte	0x1b
	.byte	0x8
	.byte	0x25
	.byte	0x8
	.byte	0x13
	.byte	0xb
	.byte	0,0
	.byte	0x2
	.byte	0x16
	.byte	0x0
	.byte	0x3
	.byte	0x8
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0xb
	.byte	0x49
	.byte	0x13
	.byte	0,0
	.byte	0x3
	.byte	0x24
	.byte	0x0
	.byte	0x3
	.byte	0x8
	.byte	0xb
	.byte	0xb
	.byte	0x3e
	.byte	0xb
	.byte	0,0
	.byte	0x4
	.byte	0x13
	.byte	0x1
	.byte	0x1
	.byte	0x13
	.byte	0x3
	.byte	0x8
	.byte	0xb
	.byte	0xb
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0xb
	.byte	0,0
	.byte	0x5
	.byte	0xd
	.byte	0x0
	.byte	0x3
	.byte	0x8
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0xb
	.byte	0x49
	.byte	0x13
	.byte	0x38
	.byte	0xa
	.byte	0,0
	.byte	0x6
	.byte	0xf
	.byte	0x0
	.byte	0xb
	.byte	0xb
	.byte	0x49
	.byte	0x13
	.byte	0,0
	.byte	0x7
	.byte	0xf
	.byte	0x0
	.byte	0xb
	.byte	0xb
	.byte	0,0
	.byte	0x8
	.byte	0x15
	.byte	0x1
	.byte	0x1
	.byte	0x13
	.byte	0x27
	.byte	0xc
	.byte	0x49
	.byte	0x13
	.byte	0,0
	.byte	0x9
	.byte	0x5
	.byte	0x0
	.byte	0x49
	.byte	0x13
	.byte	0,0
	.byte	0xa
	.byte	0x26
	.byte	0x0
	.byte	0x49
	.byte	0x13
	.byte	0,0
	.byte	0xb
	.byte	0x1
	.byte	0x1
	.byte	0x1
	.byte	0x13
	.byte	0x49
	.byte	0x13
	.byte	0,0
	.byte	0xc
	.byte	0x21
	.byte	0x0
	.byte	0x2f
	.byte	0xb
	.byte	0,0
	.byte	0xd
	.byte	0x13
	.byte	0x1
	.byte	0x1
	.byte	0x13
	.byte	0x3
	.byte	0x8
	.byte	0xb
	.byte	0x5
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0xb
	.byte	0,0
	.byte	0xe
	.byte	0x15
	.byte	0x1
	.byte	0x1
	.byte	0x13
	.byte	0x27
	.byte	0xc
	.byte	0,0
	.byte	0xf
	.byte	0x17
	.byte	0x1
	.byte	0x1
	.byte	0x13
	.byte	0xb
	.byte	0xb
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0xb
	.byte	0,0
	.byte	0x10
	.byte	0xd
	.byte	0x0
	.byte	0x3
	.byte	0x8
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0xb
	.byte	0x49
	.byte	0x13
	.byte	0,0
	.byte	0x11
	.byte	0x15
	.byte	0x0
	.byte	0x27
	.byte	0xc
	.byte	0,0
	.byte	0x12
	.byte	0x13
	.byte	0x1
	.byte	0x1
	.byte	0x13
	.byte	0xb
	.byte	0xb
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0xb
	.byte	0,0
	.byte	0x13
	.byte	0x4
	.byte	0x1
	.byte	0x1
	.byte	0x13
	.byte	0xb
	.byte	0xb
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0x5
	.byte	0,0
	.byte	0x14
	.byte	0x28
	.byte	0x0
	.byte	0x3
	.byte	0x8
	.byte	0x1c
	.byte	0xb
	.byte	0,0
	.byte	0x15
	.byte	0x35
	.byte	0x0
	.byte	0x49
	.byte	0x13
	.byte	0,0
	.byte	0x16
	.byte	0xd
	.byte	0x0
	.byte	0x3
	.byte	0x8
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0xb
	.byte	0x49
	.byte	0x13
	.byte	0xb
	.byte	0xb
	.byte	0xd
	.byte	0xb
	.byte	0xc
	.byte	0xb
	.byte	0x38
	.byte	0xa
	.byte	0,0
	.byte	0x17
	.byte	0x4
	.byte	0x1
	.byte	0x1
	.byte	0x13
	.byte	0xb
	.byte	0xb
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0xb
	.byte	0,0
	.byte	0x18
	.byte	0x26
	.byte	0x0
	.byte	0,0
	.byte	0x19
	.byte	0x13
	.byte	0x0
	.byte	0x3
	.byte	0x8
	.byte	0x3c
	.byte	0xc
	.byte	0,0
	.byte	0x1a
	.byte	0x4
	.byte	0x1
	.byte	0x1
	.byte	0x13
	.byte	0x3
	.byte	0x8
	.byte	0xb
	.byte	0xb
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0xb
	.byte	0,0
	.byte	0x1b
	.byte	0x28
	.byte	0x0
	.byte	0x3
	.byte	0x8
	.byte	0x1c
	.byte	0x6
	.byte	0,0
	.byte	0x1c
	.byte	0x4
	.byte	0x1
	.byte	0x1
	.byte	0x13
	.byte	0x3
	.byte	0x8
	.byte	0xb
	.byte	0xb
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0x5
	.byte	0,0
	.byte	0x1d
	.byte	0x13
	.byte	0x1
	.byte	0x1
	.byte	0x13
	.byte	0x3
	.byte	0x8
	.byte	0xb
	.byte	0x5
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0x5
	.byte	0,0
	.byte	0x1e
	.byte	0xd
	.byte	0x0
	.byte	0x3
	.byte	0x8
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0x5
	.byte	0x49
	.byte	0x13
	.byte	0x38
	.byte	0xa
	.byte	0,0
	.byte	0x1f
	.byte	0x21
	.byte	0x0
	.byte	0x2f
	.byte	0x5
	.byte	0,0
	.byte	0x20
	.byte	0x13
	.byte	0x1
	.byte	0x1
	.byte	0x13
	.byte	0x3
	.byte	0x8
	.byte	0xb
	.byte	0xb
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0x5
	.byte	0,0
	.byte	0x21
	.byte	0x34
	.byte	0x0
	.byte	0x3
	.byte	0x8
	.byte	0x3a
	.byte	0xb
	.byte	0x3b
	.byte	0xb
	.byte	0x49
	.byte	0x13
	.byte	0x3f
	.byte	0xc
	.byte	0x2
	.byte	0xa
	.byte	0,0

	.section	.debug_info
	.4byte	0x396a
	.2byte	0x2
	.4byte	.debug_abbrev
	.byte	0x4
	.byte	0x1
	.ascii	"src/data_debugpinfo.c\000"

	.ascii	"/home/napsterisreal/Software/by_virtue_fall/fireemblem8u"
	.ascii	"\000"

	.ascii	"GNU C 2.9-arm-000512\000"

	.byte	0x1
	.byte	0x2
	.ascii	"__int32_t\000"

	.byte	0x1
	.byte	0x67
	.4byte	0x82
	.byte	0x3
	.ascii	"int\000"

	.byte	0x4
	.byte	0x5
	.byte	0x2
	.ascii	"__uint32_t\000"

	.byte	0x1
	.byte	0x68
	.4byte	0x9b
	.byte	0x3
	.ascii	"unsigned int\000"

	.byte	0x4
	.byte	0x7
	.byte	0x2
	.ascii	"ptrdiff_t\000"

	.byte	0x2
	.byte	0x6
	.4byte	0xbc
	.byte	0x3
	.ascii	"long int\000"

	.byte	0x4
	.byte	0x5
	.byte	0x2
	.ascii	"size_t\000"

	.byte	0x2
	.byte	0xa
	.4byte	0xd6
	.byte	0x3
	.ascii	"long unsigned int\000"

	.byte	0x4
	.byte	0x7
	.byte	0x2
	.ascii	"wchar_t\000"

	.byte	0x2
	.byte	0x11
	.4byte	0x82
	.byte	0x2
	.ascii	"clock_t\000"

	.byte	0x3
	.byte	0x24
	.4byte	0xd6
	.byte	0x2
	.ascii	"time_t\000"

	.byte	0x3
	.byte	0x29
	.4byte	0xbc
	.byte	0x4
	.4byte	0x1c3
	.ascii	"tm\000"

	.byte	0x24
	.byte	0x3
	.byte	0x2e
	.byte	0x5
	.ascii	"tm_sec\000"

	.byte	0x3
	.byte	0x2f
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"tm_min\000"

	.byte	0x3
	.byte	0x30
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x5
	.ascii	"tm_hour\000"

	.byte	0x3
	.byte	0x31
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x5
	.ascii	"tm_mday\000"

	.byte	0x3
	.byte	0x32
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x5
	.ascii	"tm_mon\000"

	.byte	0x3
	.byte	0x33
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x10
	.byte	0x5
	.ascii	"tm_year\000"

	.byte	0x3
	.byte	0x34
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x14
	.byte	0x5
	.ascii	"tm_wday\000"

	.byte	0x3
	.byte	0x35
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x18
	.byte	0x5
	.ascii	"tm_yday\000"

	.byte	0x3
	.byte	0x36
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x1c
	.byte	0x5
	.ascii	"tm_isdst\000"

	.byte	0x3
	.byte	0x37
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x20
	.byte	0x0
	.byte	0x2
	.ascii	"ULong\000"

	.byte	0x4
	.byte	0x1c
	.4byte	0x89
	.byte	0x4
	.4byte	0x210
	.ascii	"_glue\000"

	.byte	0xc
	.byte	0x4
	.byte	0x20
	.byte	0x5
	.ascii	"_next\000"

	.byte	0x4
	.byte	0x21
	.4byte	0x210
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"_niobs\000"

	.byte	0x4
	.byte	0x22
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x5
	.ascii	"_iobs\000"

	.byte	0x4
	.byte	0x23
	.4byte	0x371
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x1d0
	.byte	0x4
	.4byte	0x371
	.ascii	"__sFILE\000"

	.byte	0x58
	.byte	0x4
	.byte	0x23
	.byte	0x5
	.ascii	"_p\000"

	.byte	0x4
	.byte	0x67
	.4byte	0x377
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"_r\000"

	.byte	0x4
	.byte	0x68
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x5
	.ascii	"_w\000"

	.byte	0x4
	.byte	0x69
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x5
	.ascii	"_flags\000"

	.byte	0x4
	.byte	0x6a
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x5
	.ascii	"_file\000"

	.byte	0x4
	.byte	0x6b
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0xe
	.byte	0x5
	.ascii	"_bf\000"

	.byte	0x4
	.byte	0x6c
	.4byte	0x39b
	.byte	0x2
	.byte	0x23
	.byte	0x10
	.byte	0x5
	.ascii	"_lbfsize\000"

	.byte	0x4
	.byte	0x6d
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x18
	.byte	0x5
	.ascii	"_cookie\000"

	.byte	0x4
	.byte	0x70
	.4byte	0x3cb
	.byte	0x2
	.byte	0x23
	.byte	0x1c
	.byte	0x5
	.ascii	"_read\000"

	.byte	0x4
	.byte	0x72
	.4byte	0x3f5
	.byte	0x2
	.byte	0x23
	.byte	0x20
	.byte	0x5
	.ascii	"_write\000"

	.byte	0x4
	.byte	0x73
	.4byte	0x420
	.byte	0x2
	.byte	0x23
	.byte	0x24
	.byte	0x5
	.ascii	"_seek\000"

	.byte	0x4
	.byte	0x74
	.4byte	0x44b
	.byte	0x2
	.byte	0x23
	.byte	0x28
	.byte	0x5
	.ascii	"_close\000"

	.byte	0x4
	.byte	0x75
	.4byte	0x461
	.byte	0x2
	.byte	0x23
	.byte	0x2c
	.byte	0x5
	.ascii	"_ub\000"

	.byte	0x4
	.byte	0x78
	.4byte	0x39b
	.byte	0x2
	.byte	0x23
	.byte	0x30
	.byte	0x5
	.ascii	"_up\000"

	.byte	0x4
	.byte	0x79
	.4byte	0x377
	.byte	0x2
	.byte	0x23
	.byte	0x38
	.byte	0x5
	.ascii	"_ur\000"

	.byte	0x4
	.byte	0x7a
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x3c
	.byte	0x5
	.ascii	"_ubuf\000"

	.byte	0x4
	.byte	0x7d
	.4byte	0x467
	.byte	0x2
	.byte	0x23
	.byte	0x40
	.byte	0x5
	.ascii	"_nbuf\000"

	.byte	0x4
	.byte	0x7e
	.4byte	0x473
	.byte	0x2
	.byte	0x23
	.byte	0x43
	.byte	0x5
	.ascii	"_lb\000"

	.byte	0x4
	.byte	0x81
	.4byte	0x39b
	.byte	0x2
	.byte	0x23
	.byte	0x44
	.byte	0x5
	.ascii	"_blksize\000"

	.byte	0x4
	.byte	0x84
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x4c
	.byte	0x5
	.ascii	"_offset\000"

	.byte	0x4
	.byte	0x85
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x50
	.byte	0x5
	.ascii	"_data\000"

	.byte	0x4
	.byte	0x87
	.4byte	0x634
	.byte	0x2
	.byte	0x23
	.byte	0x54
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x216
	.byte	0x6
	.byte	0x4
	.4byte	0x37d
	.byte	0x3
	.ascii	"unsigned char\000"

	.byte	0x1
	.byte	0x8
	.byte	0x3
	.ascii	"short int\000"

	.byte	0x2
	.byte	0x5
	.byte	0x4
	.4byte	0x3cb
	.ascii	"__sbuf\000"

	.byte	0x8
	.byte	0x4
	.byte	0x40
	.byte	0x5
	.ascii	"_base\000"

	.byte	0x4
	.byte	0x41
	.4byte	0x377
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"_size\000"

	.byte	0x4
	.byte	0x42
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x0
	.byte	0x7
	.byte	0x4
	.byte	0x8
	.4byte	0x3e7
	.byte	0x1
	.4byte	0x82
	.byte	0x9
	.4byte	0x3cb
	.byte	0x9
	.4byte	0x3e7
	.byte	0x9
	.4byte	0x82
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x3ed
	.byte	0x3
	.ascii	"char\000"

	.byte	0x1
	.byte	0x8
	.byte	0x6
	.byte	0x4
	.4byte	0x3cd
	.byte	0x8
	.4byte	0x415
	.byte	0x1
	.4byte	0x82
	.byte	0x9
	.4byte	0x3cb
	.byte	0x9
	.4byte	0x415
	.byte	0x9
	.4byte	0x82
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x41b
	.byte	0xa
	.4byte	0x3ed
	.byte	0x6
	.byte	0x4
	.4byte	0x3fb
	.byte	0x8
	.4byte	0x440
	.byte	0x1
	.4byte	0x440
	.byte	0x9
	.4byte	0x3cb
	.byte	0x9
	.4byte	0x440
	.byte	0x9
	.4byte	0x82
	.byte	0x0
	.byte	0x3
	.ascii	"_fpos_t\000"

	.byte	0x4
	.byte	0x5
	.byte	0x6
	.byte	0x4
	.4byte	0x426
	.byte	0x8
	.4byte	0x461
	.byte	0x1
	.4byte	0x82
	.byte	0x9
	.4byte	0x3cb
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x451
	.byte	0xb
	.4byte	0x473
	.4byte	0x37d
	.byte	0xc
	.byte	0x2
	.byte	0x0
	.byte	0xb
	.4byte	0x47f
	.4byte	0x37d
	.byte	0xc
	.byte	0x0
	.byte	0x0
	.byte	0xd
	.4byte	0x634
	.ascii	"_reent\000"

	.2byte	0x2ec
	.byte	0x4
	.byte	0x87
	.byte	0x5
	.ascii	"_errno\000"

	.byte	0x4
	.byte	0x95
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"_stdin\000"

	.byte	0x4
	.byte	0x9a
	.4byte	0x371
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x5
	.ascii	"_stdout\000"

	.byte	0x4
	.byte	0x9a
	.4byte	0x371
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x5
	.ascii	"_stderr\000"

	.byte	0x4
	.byte	0x9a
	.4byte	0x371
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x5
	.ascii	"_inc\000"

	.byte	0x4
	.byte	0x9c
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x10
	.byte	0x5
	.ascii	"_emergency\000"

	.byte	0x4
	.byte	0x9d
	.4byte	0x63a
	.byte	0x2
	.byte	0x23
	.byte	0x14
	.byte	0x5
	.ascii	"_current_category\000"

	.byte	0x4
	.byte	0x9f
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x30
	.byte	0x5
	.ascii	"_current_locale\000"

	.byte	0x4
	.byte	0xa0
	.4byte	0x415
	.byte	0x2
	.byte	0x23
	.byte	0x34
	.byte	0x5
	.ascii	"__sdidinit\000"

	.byte	0x4
	.byte	0xa2
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x38
	.byte	0x5
	.ascii	"__cleanup\000"

	.byte	0x4
	.byte	0xa4
	.4byte	0x652
	.byte	0x2
	.byte	0x23
	.byte	0x3c
	.byte	0x5
	.ascii	"_result\000"

	.byte	0x4
	.byte	0xa7
	.4byte	0x6c4
	.byte	0x2
	.byte	0x23
	.byte	0x40
	.byte	0x5
	.ascii	"_result_k\000"

	.byte	0x4
	.byte	0xa8
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x44
	.byte	0x5
	.ascii	"_p5s\000"

	.byte	0x4
	.byte	0xa9
	.4byte	0x6c4
	.byte	0x2
	.byte	0x23
	.byte	0x48
	.byte	0x5
	.ascii	"_freelist\000"

	.byte	0x4
	.byte	0xaa
	.4byte	0x6ca
	.byte	0x2
	.byte	0x23
	.byte	0x4c
	.byte	0x5
	.ascii	"_cvtlen\000"

	.byte	0x4
	.byte	0xad
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x50
	.byte	0x5
	.ascii	"_cvtbuf\000"

	.byte	0x4
	.byte	0xae
	.4byte	0x3e7
	.byte	0x2
	.byte	0x23
	.byte	0x54
	.byte	0x5
	.ascii	"_new\000"

	.byte	0x4
	.byte	0xc3
	.4byte	0x6d0
	.byte	0x2
	.byte	0x23
	.byte	0x58
	.byte	0x5
	.ascii	"_atexit\000"

	.byte	0x4
	.byte	0xc6
	.4byte	0x735
	.byte	0x3
	.byte	0x23
	.byte	0xc8,0x2
	.byte	0x5
	.ascii	"_atexit0\000"

	.byte	0x4
	.byte	0xc7
	.4byte	0x6f6
	.byte	0x3
	.byte	0x23
	.byte	0xcc,0x2
	.byte	0x5
	.ascii	"_sig_func\000"

	.byte	0x4
	.byte	0xca
	.4byte	0x747
	.byte	0x3
	.byte	0x23
	.byte	0xd4,0x3
	.byte	0x5
	.ascii	"__sglue\000"

	.byte	0x4
	.byte	0xcf
	.4byte	0x1d0
	.byte	0x3
	.byte	0x23
	.byte	0xd8,0x3
	.byte	0x5
	.ascii	"__sf\000"

	.byte	0x4
	.byte	0xd0
	.4byte	0x753
	.byte	0x3
	.byte	0x23
	.byte	0xe4,0x3
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x47f
	.byte	0xb
	.4byte	0x646
	.4byte	0x3ed
	.byte	0xc
	.byte	0x18
	.byte	0x0
	.byte	0xe
	.4byte	0x652
	.byte	0x1
	.byte	0x9
	.4byte	0x634
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x646
	.byte	0x4
	.4byte	0x6c4
	.ascii	"_Bigint\000"

	.byte	0x18
	.byte	0x4
	.byte	0x27
	.byte	0x5
	.ascii	"_next\000"

	.byte	0x4
	.byte	0x28
	.4byte	0x6c4
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"_k\000"

	.byte	0x4
	.byte	0x29
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x5
	.ascii	"_maxwds\000"

	.byte	0x4
	.byte	0x29
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x5
	.ascii	"_sign\000"

	.byte	0x4
	.byte	0x29
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x5
	.ascii	"_wds\000"

	.byte	0x4
	.byte	0x29
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x10
	.byte	0x5
	.ascii	"_x\000"

	.byte	0x4
	.byte	0x2a
	.4byte	0x842
	.byte	0x2
	.byte	0x23
	.byte	0x14
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x658
	.byte	0x6
	.byte	0x4
	.4byte	0x6c4
	.byte	0xf
	.4byte	0x6f6
	.byte	0xf0
	.byte	0x4
	.byte	0xc3
	.byte	0x10
	.ascii	"_reent\000"

	.byte	0x4
	.byte	0xb9
	.4byte	0x773
	.byte	0x10
	.ascii	"_unused\000"

	.byte	0x4
	.byte	0xc2
	.4byte	0x7f1
	.byte	0x0
	.byte	0x4
	.4byte	0x735
	.ascii	"_atexit\000"

	.byte	0x88
	.byte	0x4
	.byte	0x33
	.byte	0x5
	.ascii	"_next\000"

	.byte	0x4
	.byte	0x34
	.4byte	0x735
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"_ind\000"

	.byte	0x4
	.byte	0x35
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x5
	.ascii	"_fns\000"

	.byte	0x4
	.byte	0x36
	.4byte	0x75f
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x6f6
	.byte	0xe
	.4byte	0x747
	.byte	0x1
	.byte	0x9
	.4byte	0x82
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x74d
	.byte	0x6
	.byte	0x4
	.4byte	0x73b
	.byte	0xb
	.4byte	0x75f
	.4byte	0x216
	.byte	0xc
	.byte	0x2
	.byte	0x0
	.byte	0xb
	.4byte	0x76b
	.4byte	0x76d
	.byte	0xc
	.byte	0x1f
	.byte	0x0
	.byte	0x11
	.byte	0x1
	.byte	0x6
	.byte	0x4
	.4byte	0x76b
	.byte	0x12
	.4byte	0x7f1
	.byte	0x4c
	.byte	0x4
	.byte	0xb9
	.byte	0x5
	.ascii	"_rand_next\000"

	.byte	0x4
	.byte	0xb4
	.4byte	0x9b
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"_strtok_last\000"

	.byte	0x4
	.byte	0xb5
	.4byte	0x3e7
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x5
	.ascii	"_asctime_buf\000"

	.byte	0x4
	.byte	0xb6
	.4byte	0x836
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x5
	.ascii	"_localtime_buf\000"

	.byte	0x4
	.byte	0xb7
	.4byte	0x117
	.byte	0x2
	.byte	0x23
	.byte	0x24
	.byte	0x5
	.ascii	"_gamma_signgam\000"

	.byte	0x4
	.byte	0xb8
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x48
	.byte	0x0
	.byte	0x12
	.4byte	0x81e
	.byte	0xf0
	.byte	0x4
	.byte	0xc2
	.byte	0x5
	.ascii	"_nextf\000"

	.byte	0x4
	.byte	0xc0
	.4byte	0x81e
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"_nmalloc\000"

	.byte	0x4
	.byte	0xc1
	.4byte	0x82a
	.byte	0x2
	.byte	0x23
	.byte	0x78
	.byte	0x0
	.byte	0xb
	.4byte	0x82a
	.4byte	0x377
	.byte	0xc
	.byte	0x1d
	.byte	0x0
	.byte	0xb
	.4byte	0x836
	.4byte	0x9b
	.byte	0xc
	.byte	0x1d
	.byte	0x0
	.byte	0xb
	.4byte	0x842
	.4byte	0x3ed
	.byte	0xc
	.byte	0x19
	.byte	0x0
	.byte	0xb
	.4byte	0x84e
	.4byte	0x1c3
	.byte	0xc
	.byte	0x0
	.byte	0x0
	.byte	0x2
	.ascii	"_fpos_t\000"

	.byte	0x4
	.byte	0x4a
	.4byte	0xbc
	.byte	0x12
	.4byte	0x883
	.byte	0x8
	.byte	0x5
	.byte	0x19
	.byte	0x5
	.ascii	"quot\000"

	.byte	0x5
	.byte	0x17
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"rem\000"

	.byte	0x5
	.byte	0x18
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x0
	.byte	0x2
	.ascii	"div_t\000"

	.byte	0x5
	.byte	0x19
	.4byte	0x85d
	.byte	0x12
	.4byte	0x8b6
	.byte	0x8
	.byte	0x5
	.byte	0x1f
	.byte	0x5
	.ascii	"quot\000"

	.byte	0x5
	.byte	0x1d
	.4byte	0xbc
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"rem\000"

	.byte	0x5
	.byte	0x1e
	.4byte	0xbc
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x0
	.byte	0x2
	.ascii	"ldiv_t\000"

	.byte	0x5
	.byte	0x1f
	.4byte	0x890
	.byte	0x2
	.ascii	"int8_t\000"

	.byte	0x6
	.byte	0x23
	.4byte	0x8d2
	.byte	0x3
	.ascii	"signed char\000"

	.byte	0x1
	.byte	0x6
	.byte	0x2
	.ascii	"int16_t\000"

	.byte	0x6
	.byte	0x24
	.4byte	0x38e
	.byte	0x2
	.ascii	"int32_t\000"

	.byte	0x6
	.byte	0x25
	.4byte	0x82
	.byte	0x2
	.ascii	"int64_t\000"

	.byte	0x6
	.byte	0x26
	.4byte	0x90e
	.byte	0x3
	.ascii	"long long int\000"

	.byte	0x8
	.byte	0x5
	.byte	0x2
	.ascii	"uint8_t\000"

	.byte	0x6
	.byte	0x27
	.4byte	0x37d
	.byte	0x2
	.ascii	"uint16_t\000"

	.byte	0x6
	.byte	0x28
	.4byte	0x93e
	.byte	0x3
	.ascii	"short unsigned int\000"

	.byte	0x2
	.byte	0x7
	.byte	0x2
	.ascii	"uint32_t\000"

	.byte	0x6
	.byte	0x29
	.4byte	0x9b
	.byte	0x2
	.ascii	"uint64_t\000"

	.byte	0x6
	.byte	0x2a
	.4byte	0x974
	.byte	0x3
	.ascii	"long long unsigned int\000"

	.byte	0x8
	.byte	0x7
	.byte	0x2
	.ascii	"int_least8_t\000"

	.byte	0x6
	.byte	0x2e
	.4byte	0x8d2
	.byte	0x2
	.ascii	"int_least16_t\000"

	.byte	0x6
	.byte	0x2f
	.4byte	0x38e
	.byte	0x2
	.ascii	"int_least32_t\000"

	.byte	0x6
	.byte	0x30
	.4byte	0x82
	.byte	0x2
	.ascii	"int_least64_t\000"

	.byte	0x6
	.byte	0x31
	.4byte	0x90e
	.byte	0x2
	.ascii	"uint_least8_t\000"

	.byte	0x6
	.byte	0x32
	.4byte	0x37d
	.byte	0x2
	.ascii	"uint_least16_t\000"

	.byte	0x6
	.byte	0x33
	.4byte	0x93e
	.byte	0x2
	.ascii	"uint_least32_t\000"

	.byte	0x6
	.byte	0x34
	.4byte	0x9b
	.byte	0x2
	.ascii	"uint_least64_t\000"

	.byte	0x6
	.byte	0x35
	.4byte	0x974
	.byte	0x2
	.ascii	"int_fast8_t\000"

	.byte	0x6
	.byte	0x39
	.4byte	0x82
	.byte	0x2
	.ascii	"int_fast16_t\000"

	.byte	0x6
	.byte	0x3a
	.4byte	0x82
	.byte	0x2
	.ascii	"int_fast32_t\000"

	.byte	0x6
	.byte	0x3b
	.4byte	0x82
	.byte	0x2
	.ascii	"int_fast64_t\000"

	.byte	0x6
	.byte	0x3c
	.4byte	0x90e
	.byte	0x2
	.ascii	"uint_fast8_t\000"

	.byte	0x6
	.byte	0x3d
	.4byte	0x9b
	.byte	0x2
	.ascii	"uint_fast16_t\000"

	.byte	0x6
	.byte	0x3e
	.4byte	0x9b
	.byte	0x2
	.ascii	"uint_fast32_t\000"

	.byte	0x6
	.byte	0x3f
	.4byte	0x9b
	.byte	0x2
	.ascii	"uint_fast64_t\000"

	.byte	0x6
	.byte	0x40
	.4byte	0x974
	.byte	0x2
	.ascii	"intptr_t\000"

	.byte	0x6
	.byte	0x44
	.4byte	0x82
	.byte	0x2
	.ascii	"uintptr_t\000"

	.byte	0x6
	.byte	0x45
	.4byte	0x9b
	.byte	0x2
	.ascii	"intmax_t\000"

	.byte	0x6
	.byte	0x49
	.4byte	0x90e
	.byte	0x2
	.ascii	"uintmax_t\000"

	.byte	0x6
	.byte	0x4a
	.4byte	0x974
	.byte	0x13
	.4byte	0xb7d
	.byte	0x4
	.byte	0x7
	.2byte	0x221
	.byte	0x14
	.ascii	"BLEND_EFFECT_NONE\000"

	.byte	0x0
	.byte	0x14
	.ascii	"BLEND_EFFECT_ALPHA\000"

	.byte	0x1
	.byte	0x14
	.ascii	"BLEND_EFFECT_BRIGHTEN\000"

	.byte	0x2
	.byte	0x14
	.ascii	"BLEND_EFFECT_DARKEN\000"

	.byte	0x3
	.byte	0x0
	.byte	0x2
	.ascii	"u8\000"

	.byte	0x8
	.byte	0x6
	.4byte	0x91f
	.byte	0x2
	.ascii	"u16\000"

	.byte	0x8
	.byte	0x7
	.4byte	0x92e
	.byte	0x2
	.ascii	"u32\000"

	.byte	0x8
	.byte	0x8
	.4byte	0x954
	.byte	0x2
	.ascii	"u64\000"

	.byte	0x8
	.byte	0x9
	.4byte	0x964
	.byte	0x2
	.ascii	"s8\000"

	.byte	0x8
	.byte	0xa
	.4byte	0x8c4
	.byte	0x2
	.ascii	"s16\000"

	.byte	0x8
	.byte	0xb
	.4byte	0x8e1
	.byte	0x2
	.ascii	"s32\000"

	.byte	0x8
	.byte	0xc
	.4byte	0x8f0
	.byte	0x2
	.ascii	"s64\000"

	.byte	0x8
	.byte	0xd
	.4byte	0x8ff
	.byte	0x2
	.ascii	"vu8\000"

	.byte	0x8
	.byte	0xf
	.4byte	0xbde
	.byte	0x15
	.4byte	0xb7d
	.byte	0x2
	.ascii	"vu16\000"

	.byte	0x8
	.byte	0x10
	.4byte	0xbef
	.byte	0x15
	.4byte	0xb87
	.byte	0x2
	.ascii	"vu32\000"

	.byte	0x8
	.byte	0x11
	.4byte	0xc00
	.byte	0x15
	.4byte	0xb92
	.byte	0x2
	.ascii	"vu64\000"

	.byte	0x8
	.byte	0x12
	.4byte	0xc11
	.byte	0x15
	.4byte	0xb9d
	.byte	0x2
	.ascii	"vs8\000"

	.byte	0x8
	.byte	0x13
	.4byte	0xc21
	.byte	0x15
	.4byte	0xba8
	.byte	0x2
	.ascii	"vs16\000"

	.byte	0x8
	.byte	0x14
	.4byte	0xc32
	.byte	0x15
	.4byte	0xbb2
	.byte	0x2
	.ascii	"vs32\000"

	.byte	0x8
	.byte	0x15
	.4byte	0xc43
	.byte	0x15
	.4byte	0xbbd
	.byte	0x2
	.ascii	"vs64\000"

	.byte	0x8
	.byte	0x16
	.4byte	0xc54
	.byte	0x15
	.4byte	0xbc8
	.byte	0x2
	.ascii	"f32\000"

	.byte	0x8
	.byte	0x18
	.4byte	0xc64
	.byte	0x3
	.ascii	"float\000"

	.byte	0x4
	.byte	0x4
	.byte	0x2
	.ascii	"f64\000"

	.byte	0x8
	.byte	0x19
	.4byte	0xc78
	.byte	0x3
	.ascii	"double\000"

	.byte	0x8
	.byte	0x4
	.byte	0x2
	.ascii	"bool8\000"

	.byte	0x8
	.byte	0x1b
	.4byte	0xb7d
	.byte	0x2
	.ascii	"bool16\000"

	.byte	0x8
	.byte	0x1c
	.4byte	0xb87
	.byte	0x2
	.ascii	"bool32\000"

	.byte	0x8
	.byte	0x1d
	.4byte	0xb92
	.byte	0x4
	.4byte	0xd01
	.ascii	"PlttData\000"

	.byte	0x4
	.byte	0x8
	.byte	0x20
	.byte	0x16
	.ascii	"r\000"

	.byte	0x8
	.byte	0x21
	.4byte	0xb87
	.byte	0x2
	.byte	0x5
	.byte	0xb
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"g\000"

	.byte	0x8
	.byte	0x22
	.4byte	0xb87
	.byte	0x2
	.byte	0x5
	.byte	0x6
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"b\000"

	.byte	0x8
	.byte	0x23
	.4byte	0xb87
	.byte	0x2
	.byte	0x5
	.byte	0x1
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"unused_15\000"

	.byte	0x8
	.byte	0x24
	.4byte	0xb87
	.byte	0x2
	.byte	0x1
	.byte	0x0
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x0
	.byte	0x4
	.4byte	0xe17
	.ascii	"OamData\000"

	.byte	0x8
	.byte	0x8
	.byte	0x28
	.byte	0x16
	.ascii	"y\000"

	.byte	0x8
	.byte	0x29
	.4byte	0xb92
	.byte	0x4
	.byte	0x8
	.byte	0x18
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"affineMode\000"

	.byte	0x8
	.byte	0x2a
	.4byte	0xb92
	.byte	0x4
	.byte	0x2
	.byte	0x16
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"objMode\000"

	.byte	0x8
	.byte	0x2b
	.4byte	0xb92
	.byte	0x4
	.byte	0x2
	.byte	0x14
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"mosaic\000"

	.byte	0x8
	.byte	0x2c
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0x13
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"bpp\000"

	.byte	0x8
	.byte	0x2d
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0x12
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"shape\000"

	.byte	0x8
	.byte	0x2e
	.4byte	0xb92
	.byte	0x4
	.byte	0x2
	.byte	0x10
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"x\000"

	.byte	0x8
	.byte	0x30
	.4byte	0xb92
	.byte	0x4
	.byte	0x9
	.byte	0x7
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"matrixNum\000"

	.byte	0x8
	.byte	0x31
	.4byte	0xb92
	.byte	0x4
	.byte	0x5
	.byte	0x2
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"size\000"

	.byte	0x8
	.byte	0x32
	.4byte	0xb92
	.byte	0x4
	.byte	0x2
	.byte	0x0
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"tileNum\000"

	.byte	0x8
	.byte	0x34
	.4byte	0xb87
	.byte	0x2
	.byte	0xa
	.byte	0x6
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x16
	.ascii	"priority\000"

	.byte	0x8
	.byte	0x35
	.4byte	0xb87
	.byte	0x2
	.byte	0x2
	.byte	0x4
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x16
	.ascii	"paletteNum\000"

	.byte	0x8
	.byte	0x36
	.4byte	0xb87
	.byte	0x2
	.byte	0x4
	.byte	0x0
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x5
	.ascii	"affineParam\000"

	.byte	0x8
	.byte	0x37
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x6
	.byte	0x0
	.byte	0x4
	.4byte	0xe96
	.ascii	"BgAffineSrcData\000"

	.byte	0x14
	.byte	0x8
	.byte	0x4e
	.byte	0x5
	.ascii	"texX\000"

	.byte	0x8
	.byte	0x4f
	.4byte	0xbbd
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"texY\000"

	.byte	0x8
	.byte	0x50
	.4byte	0xbbd
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x5
	.ascii	"scrX\000"

	.byte	0x8
	.byte	0x51
	.4byte	0xbb2
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x5
	.ascii	"scrY\000"

	.byte	0x8
	.byte	0x52
	.4byte	0xbb2
	.byte	0x2
	.byte	0x23
	.byte	0xa
	.byte	0x5
	.ascii	"sx\000"

	.byte	0x8
	.byte	0x53
	.4byte	0xbb2
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x5
	.ascii	"sy\000"

	.byte	0x8
	.byte	0x54
	.4byte	0xbb2
	.byte	0x2
	.byte	0x23
	.byte	0xe
	.byte	0x5
	.ascii	"alpha\000"

	.byte	0x8
	.byte	0x55
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x10
	.byte	0x0
	.byte	0x4
	.4byte	0xefd
	.ascii	"BgAffineDstData\000"

	.byte	0x10
	.byte	0x8
	.byte	0x59
	.byte	0x5
	.ascii	"pa\000"

	.byte	0x8
	.byte	0x5a
	.4byte	0xbb2
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"pb\000"

	.byte	0x8
	.byte	0x5b
	.4byte	0xbb2
	.byte	0x2
	.byte	0x23
	.byte	0x2
	.byte	0x5
	.ascii	"pc\000"

	.byte	0x8
	.byte	0x5c
	.4byte	0xbb2
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x5
	.ascii	"pd\000"

	.byte	0x8
	.byte	0x5d
	.4byte	0xbb2
	.byte	0x2
	.byte	0x23
	.byte	0x6
	.byte	0x5
	.ascii	"dx\000"

	.byte	0x8
	.byte	0x5e
	.4byte	0xbbd
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x5
	.ascii	"dy\000"

	.byte	0x8
	.byte	0x5f
	.4byte	0xbbd
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x0
	.byte	0x4
	.4byte	0xf4c
	.ascii	"ObjAffineSrcData\000"

	.byte	0x8
	.byte	0x8
	.byte	0x63
	.byte	0x5
	.ascii	"xScale\000"

	.byte	0x8
	.byte	0x64
	.4byte	0xbb2
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"yScale\000"

	.byte	0x8
	.byte	0x65
	.4byte	0xbb2
	.byte	0x2
	.byte	0x23
	.byte	0x2
	.byte	0x5
	.ascii	"rotation\000"

	.byte	0x8
	.byte	0x66
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x0
	.byte	0x4
	.4byte	0x1037
	.ascii	"SioMultiCnt\000"

	.byte	0x4
	.byte	0x8
	.byte	0x6b
	.byte	0x16
	.ascii	"baudRate\000"

	.byte	0x8
	.byte	0x6c
	.4byte	0xb87
	.byte	0x2
	.byte	0x2
	.byte	0xe
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"si\000"

	.byte	0x8
	.byte	0x6d
	.4byte	0xb87
	.byte	0x2
	.byte	0x1
	.byte	0xd
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"sd\000"

	.byte	0x8
	.byte	0x6e
	.4byte	0xb87
	.byte	0x2
	.byte	0x1
	.byte	0xc
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"id\000"

	.byte	0x8
	.byte	0x6f
	.4byte	0xb87
	.byte	0x2
	.byte	0x2
	.byte	0xa
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"error\000"

	.byte	0x8
	.byte	0x70
	.4byte	0xb87
	.byte	0x2
	.byte	0x1
	.byte	0x9
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"enable\000"

	.byte	0x8
	.byte	0x71
	.4byte	0xb87
	.byte	0x2
	.byte	0x1
	.byte	0x8
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"unused_11_8\000"

	.byte	0x8
	.byte	0x72
	.4byte	0xb87
	.byte	0x2
	.byte	0x4
	.byte	0x4
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"mode\000"

	.byte	0x8
	.byte	0x73
	.4byte	0xb87
	.byte	0x2
	.byte	0x2
	.byte	0x2
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"intrEnable\000"

	.byte	0x8
	.byte	0x74
	.4byte	0xb87
	.byte	0x2
	.byte	0x1
	.byte	0x1
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"unused_15\000"

	.byte	0x8
	.byte	0x75
	.4byte	0xb87
	.byte	0x2
	.byte	0x1
	.byte	0x0
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"data\000"

	.byte	0x8
	.byte	0x76
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x2
	.byte	0x0
	.byte	0x4
	.4byte	0x115d
	.ascii	"WaitCnt\000"

	.byte	0x4
	.byte	0x8
	.byte	0x82
	.byte	0x16
	.ascii	"sramWait\000"

	.byte	0x8
	.byte	0x83
	.4byte	0xb87
	.byte	0x2
	.byte	0x2
	.byte	0xe
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"rom0_1stAcc\000"

	.byte	0x8
	.byte	0x84
	.4byte	0xb87
	.byte	0x2
	.byte	0x2
	.byte	0xc
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"rom0_2ndAcc\000"

	.byte	0x8
	.byte	0x85
	.4byte	0xb87
	.byte	0x2
	.byte	0x1
	.byte	0xb
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"rom1_1stAcc\000"

	.byte	0x8
	.byte	0x86
	.4byte	0xb87
	.byte	0x2
	.byte	0x2
	.byte	0x9
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"rom1_2ndAcc\000"

	.byte	0x8
	.byte	0x87
	.4byte	0xb87
	.byte	0x2
	.byte	0x1
	.byte	0x8
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"rom2_1stAcc\000"

	.byte	0x8
	.byte	0x88
	.4byte	0xb87
	.byte	0x2
	.byte	0x2
	.byte	0x6
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"rom2_2ndAcc\000"

	.byte	0x8
	.byte	0x89
	.4byte	0xb87
	.byte	0x2
	.byte	0x1
	.byte	0x5
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"phiTerminalClock\000"

	.byte	0x8
	.byte	0x8a
	.4byte	0xb87
	.byte	0x2
	.byte	0x2
	.byte	0x3
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"dummy\000"

	.byte	0x8
	.byte	0x8b
	.4byte	0xb87
	.byte	0x2
	.byte	0x1
	.byte	0x2
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"prefetchBufEnable\000"

	.byte	0x8
	.byte	0x8c
	.4byte	0xb87
	.byte	0x2
	.byte	0x1
	.byte	0x1
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"gamePakType\000"

	.byte	0x8
	.byte	0x8d
	.4byte	0xb87
	.byte	0x2
	.byte	0x1
	.byte	0x0
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x0
	.byte	0x4
	.4byte	0x1313
	.ascii	"MultiBootParam\000"

	.byte	0x4c
	.byte	0x9
	.byte	0xa
	.byte	0x5
	.ascii	"system_work\000"

	.byte	0x9
	.byte	0xb
	.4byte	0x1313
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"handshake_data\000"

	.byte	0x9
	.byte	0xc
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x14
	.byte	0x5
	.ascii	"padding\000"

	.byte	0x9
	.byte	0xd
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x15
	.byte	0x5
	.ascii	"handshake_timeout\000"

	.byte	0x9
	.byte	0xe
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x16
	.byte	0x5
	.ascii	"probe_count\000"

	.byte	0x9
	.byte	0xf
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x18
	.byte	0x5
	.ascii	"client_data\000"

	.byte	0x9
	.byte	0x10
	.4byte	0x131f
	.byte	0x2
	.byte	0x23
	.byte	0x19
	.byte	0x5
	.ascii	"palette_data\000"

	.byte	0x9
	.byte	0x11
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x1c
	.byte	0x5
	.ascii	"response_bit\000"

	.byte	0x9
	.byte	0x12
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x1d
	.byte	0x5
	.ascii	"client_bit\000"

	.byte	0x9
	.byte	0x13
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x1e
	.byte	0x5
	.ascii	"reserved1\000"

	.byte	0x9
	.byte	0x14
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x1f
	.byte	0x5
	.ascii	"boot_srcp\000"

	.byte	0x9
	.byte	0x15
	.4byte	0x132b
	.byte	0x2
	.byte	0x23
	.byte	0x20
	.byte	0x5
	.ascii	"boot_endp\000"

	.byte	0x9
	.byte	0x16
	.4byte	0x132b
	.byte	0x2
	.byte	0x23
	.byte	0x24
	.byte	0x5
	.ascii	"masterp\000"

	.byte	0x9
	.byte	0x17
	.4byte	0x1336
	.byte	0x2
	.byte	0x23
	.byte	0x28
	.byte	0x5
	.ascii	"reserved2\000"

	.byte	0x9
	.byte	0x18
	.4byte	0x133c
	.byte	0x2
	.byte	0x23
	.byte	0x2c
	.byte	0x5
	.ascii	"system_work2\000"

	.byte	0x9
	.byte	0x19
	.4byte	0x1348
	.byte	0x2
	.byte	0x23
	.byte	0x38
	.byte	0x5
	.ascii	"sendflag\000"

	.byte	0x9
	.byte	0x1a
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x48
	.byte	0x5
	.ascii	"probe_target_bit\000"

	.byte	0x9
	.byte	0x1b
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x49
	.byte	0x5
	.ascii	"check_wait\000"

	.byte	0x9
	.byte	0x1c
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x4a
	.byte	0x5
	.ascii	"server_type\000"

	.byte	0x9
	.byte	0x1d
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x4b
	.byte	0x0
	.byte	0xb
	.4byte	0x131f
	.4byte	0xb92
	.byte	0xc
	.byte	0x4
	.byte	0x0
	.byte	0xb
	.4byte	0x132b
	.4byte	0xb7d
	.byte	0xc
	.byte	0x2
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x1331
	.byte	0xa
	.4byte	0xb7d
	.byte	0x6
	.byte	0x4
	.4byte	0xb7d
	.byte	0xb
	.4byte	0x1348
	.4byte	0x1336
	.byte	0xc
	.byte	0x2
	.byte	0x0
	.byte	0xb
	.4byte	0x1354
	.4byte	0xb92
	.byte	0xc
	.byte	0x3
	.byte	0x0
	.byte	0x2
	.ascii	"bool\000"

	.byte	0xa
	.byte	0x8
	.4byte	0xba8
	.byte	0x17
	.4byte	0x1378
	.byte	0x4
	.byte	0xa
	.byte	0x9
	.byte	0x14
	.ascii	"false\000"

	.byte	0x0
	.byte	0x14
	.ascii	"true\000"

	.byte	0x1
	.byte	0x0
	.byte	0x4
	.4byte	0x15d3
	.ascii	"Proc\000"

	.byte	0x6c
	.byte	0xa
	.byte	0x10
	.byte	0x5
	.ascii	"proc_script\000"

	.byte	0xb
	.byte	0x43
	.4byte	0x1619
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"proc_scrCur\000"

	.byte	0xb
	.byte	0x43
	.4byte	0x1619
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x5
	.ascii	"proc_endCb\000"

	.byte	0xb
	.byte	0x43
	.4byte	0x1632
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x5
	.ascii	"proc_idleCb\000"

	.byte	0xb
	.byte	0x43
	.4byte	0x1632
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x5
	.ascii	"proc_name\000"

	.byte	0xb
	.byte	0x43
	.4byte	0x415
	.byte	0x2
	.byte	0x23
	.byte	0x10
	.byte	0x5
	.ascii	"proc_parent\000"

	.byte	0xb
	.byte	0x43
	.4byte	0x1630
	.byte	0x2
	.byte	0x23
	.byte	0x14
	.byte	0x5
	.ascii	"proc_child\000"

	.byte	0xb
	.byte	0x43
	.4byte	0x1630
	.byte	0x2
	.byte	0x23
	.byte	0x18
	.byte	0x5
	.ascii	"proc_next\000"

	.byte	0xb
	.byte	0x43
	.4byte	0x1630
	.byte	0x2
	.byte	0x23
	.byte	0x1c
	.byte	0x5
	.ascii	"proc_prev\000"

	.byte	0xb
	.byte	0x43
	.4byte	0x1630
	.byte	0x2
	.byte	0x23
	.byte	0x20
	.byte	0x5
	.ascii	"proc_sleepTime\000"

	.byte	0xb
	.byte	0x43
	.4byte	0xbb2
	.byte	0x2
	.byte	0x23
	.byte	0x24
	.byte	0x5
	.ascii	"proc_mark\000"

	.byte	0xb
	.byte	0x43
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x26
	.byte	0x5
	.ascii	"proc_flags\000"

	.byte	0xb
	.byte	0x43
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x27
	.byte	0x5
	.ascii	"proc_lockCnt\000"

	.byte	0xb
	.byte	0x43
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x28
	.byte	0x5
	.ascii	"x\000"

	.byte	0xb
	.byte	0x45
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x2c
	.byte	0x5
	.ascii	"y\000"

	.byte	0xb
	.byte	0x45
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x30
	.byte	0x5
	.ascii	"unk34\000"

	.byte	0xb
	.byte	0x46
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x34
	.byte	0x5
	.ascii	"unk38\000"

	.byte	0xb
	.byte	0x47
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x38
	.byte	0x5
	.ascii	"unk3C\000"

	.byte	0xb
	.byte	0x48
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x3c
	.byte	0x5
	.ascii	"unk40\000"

	.byte	0xb
	.byte	0x49
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x40
	.byte	0x5
	.ascii	"pad38\000"

	.byte	0xb
	.byte	0x4b
	.4byte	0x1638
	.byte	0x2
	.byte	0x23
	.byte	0x44
	.byte	0x5
	.ascii	"unk4A\000"

	.byte	0xb
	.byte	0x4d
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0x4a
	.byte	0x5
	.ascii	"unk4C\000"

	.byte	0xb
	.byte	0x50
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0x4c
	.byte	0x5
	.ascii	"unk4E\000"

	.byte	0xb
	.byte	0x51
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0x4e
	.byte	0x5
	.ascii	"unk50\000"

	.byte	0xb
	.byte	0x52
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0x50
	.byte	0x5
	.ascii	"unk52\000"

	.byte	0xb
	.byte	0x54
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x52
	.byte	0x5
	.ascii	"ptr\000"

	.byte	0xb
	.byte	0x56
	.4byte	0x3cb
	.byte	0x2
	.byte	0x23
	.byte	0x54
	.byte	0x5
	.ascii	"unk58\000"

	.byte	0xb
	.byte	0x57
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x58
	.byte	0x5
	.ascii	"unk5C\000"

	.byte	0xb
	.byte	0x58
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x5c
	.byte	0x5
	.ascii	"unk60\000"

	.byte	0xb
	.byte	0x59
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x60
	.byte	0x5
	.ascii	"unk64\000"

	.byte	0xb
	.byte	0x5a
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0x64
	.byte	0x5
	.ascii	"unk66\000"

	.byte	0xb
	.byte	0x5b
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0x66
	.byte	0x5
	.ascii	"unk68\000"

	.byte	0xb
	.byte	0x5c
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0x68
	.byte	0x5
	.ascii	"unk6A\000"

	.byte	0xb
	.byte	0x5d
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0x6a
	.byte	0x0
	.byte	0x4
	.4byte	0x1619
	.ascii	"ProcCmd\000"

	.byte	0x8
	.byte	0xb
	.byte	0xa
	.byte	0x5
	.ascii	"opcode\000"

	.byte	0xb
	.byte	0xb
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"dataImm\000"

	.byte	0xb
	.byte	0xc
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0x2
	.byte	0x5
	.ascii	"dataPtr\000"

	.byte	0xb
	.byte	0xd
	.4byte	0x1644
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x161f
	.byte	0xa
	.4byte	0x15d3
	.byte	0xe
	.4byte	0x1630
	.byte	0x1
	.byte	0x9
	.4byte	0x1630
	.byte	0x0
	.byte	0x7
	.byte	0x4
	.byte	0x6
	.byte	0x4
	.4byte	0x1624
	.byte	0xb
	.4byte	0x1644
	.4byte	0xb7d
	.byte	0xc
	.byte	0x5
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x164a
	.byte	0x18
	.byte	0x19
	.ascii	"Unit\000"

	.byte	0x1
	.byte	0x19
	.ascii	"BattleUnit\000"

	.byte	0x1
	.byte	0x19
	.ascii	"UnitDefinition\000"

	.byte	0x1
	.byte	0x19
	.ascii	"Trap\000"

	.byte	0x1
	.byte	0x19
	.ascii	"BattleHit\000"

	.byte	0x1
	.byte	0x19
	.ascii	"PopupInstruction\000"

	.byte	0x1
	.byte	0x19
	.ascii	"MAInfoFrameProc\000"

	.byte	0x1
	.byte	0x19
	.ascii	"MAExpBarProc\000"

	.byte	0x1
	.byte	0x19
	.ascii	"ProcAtMenu\000"

	.byte	0x1
	.byte	0x19
	.ascii	"PrepUnitList\000"

	.byte	0x1
	.byte	0x19
	.ascii	"Text\000"

	.byte	0x1
	.byte	0x19
	.ascii	"Anim\000"

	.byte	0x1
	.byte	0x1a
	.4byte	0x1713
	.ascii	"glb_pos\000"

	.byte	0x4
	.byte	0xa
	.byte	0x23
	.byte	0x14
	.ascii	"POS_L\000"

	.byte	0x0
	.byte	0x14
	.ascii	"POS_R\000"

	.byte	0x1
	.byte	0x1b
	.ascii	"POS_INVALID\000"

	.4byte	0xffffffff
	.byte	0x0
	.byte	0x4
	.4byte	0x173d
	.ascii	"BgCoords\000"

	.byte	0x4
	.byte	0xa
	.byte	0x2a
	.byte	0x5
	.ascii	"x\000"

	.byte	0xa
	.byte	0x2b
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"y\000"

	.byte	0xa
	.byte	0x2c
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x2
	.byte	0x0
	.byte	0x4
	.4byte	0x1776
	.ascii	"Struct0858791C\000"

	.byte	0x8
	.byte	0xa
	.byte	0x30
	.byte	0x5
	.ascii	"filler0\000"

	.byte	0xa
	.byte	0x31
	.4byte	0x1776
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"unk2\000"

	.byte	0xa
	.byte	0x32
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x0
	.byte	0xb
	.4byte	0x1782
	.4byte	0xb7d
	.byte	0xc
	.byte	0x3
	.byte	0x0
	.byte	0x2
	.ascii	"InterruptHandler\000"

	.byte	0xa
	.byte	0x35
	.4byte	0x76d
	.byte	0x4
	.4byte	0x17c0
	.ascii	"Vec2\000"

	.byte	0x4
	.byte	0xa
	.byte	0x37
	.byte	0x5
	.ascii	"x\000"

	.byte	0xa
	.byte	0x37
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"y\000"

	.byte	0xa
	.byte	0x37
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0x2
	.byte	0x0
	.byte	0x4
	.4byte	0x17e7
	.ascii	"Vec2u\000"

	.byte	0x4
	.byte	0xa
	.byte	0x38
	.byte	0x5
	.ascii	"x\000"

	.byte	0xa
	.byte	0x38
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"y\000"

	.byte	0xa
	.byte	0x38
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x2
	.byte	0x0
	.byte	0x4
	.4byte	0x180e
	.ascii	"Vec2l\000"

	.byte	0x8
	.byte	0xa
	.byte	0x39
	.byte	0x5
	.ascii	"x\000"

	.byte	0xa
	.byte	0x39
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"y\000"

	.byte	0xa
	.byte	0x39
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x0
	.byte	0x4
	.4byte	0x1aac
	.ascii	"BmSt\000"

	.byte	0x40
	.byte	0xa
	.byte	0x3c
	.byte	0x5
	.ascii	"main_loop_ended\000"

	.byte	0xa
	.byte	0x3d
	.4byte	0xba8
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"lock\000"

	.byte	0xa
	.byte	0x3f
	.4byte	0xba8
	.byte	0x2
	.byte	0x23
	.byte	0x1
	.byte	0x5
	.ascii	"gameGfxSemaphore\000"

	.byte	0xa
	.byte	0x40
	.4byte	0xba8
	.byte	0x2
	.byte	0x23
	.byte	0x2
	.byte	0x5
	.ascii	"_unk04\000"

	.byte	0xa
	.byte	0x42
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x3
	.byte	0x5
	.ascii	"gameStateBits\000"

	.byte	0xa
	.byte	0x44
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x5
	.ascii	"_unk05\000"

	.byte	0xa
	.byte	0x46
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x5
	.byte	0x5
	.ascii	"prevVCount\000"

	.byte	0xa
	.byte	0x48
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x6
	.byte	0x5
	.ascii	"_unk08\000"

	.byte	0xa
	.byte	0x4a
	.4byte	0xb92
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x5
	.ascii	"camera\000"

	.byte	0xa
	.byte	0x4c
	.4byte	0x179a
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x5
	.ascii	"cameraPrevious\000"

	.byte	0xa
	.byte	0x4d
	.4byte	0x179a
	.byte	0x2
	.byte	0x23
	.byte	0x10
	.byte	0x5
	.ascii	"playerCursor\000"

	.byte	0xa
	.byte	0x4e
	.4byte	0x179a
	.byte	0x2
	.byte	0x23
	.byte	0x14
	.byte	0x5
	.ascii	"cursorPrevious\000"

	.byte	0xa
	.byte	0x4f
	.4byte	0x179a
	.byte	0x2
	.byte	0x23
	.byte	0x18
	.byte	0x5
	.ascii	"cursorTarget\000"

	.byte	0xa
	.byte	0x50
	.4byte	0x179a
	.byte	0x2
	.byte	0x23
	.byte	0x1c
	.byte	0x5
	.ascii	"playerCursorDisplay\000"

	.byte	0xa
	.byte	0x51
	.4byte	0x179a
	.byte	0x2
	.byte	0x23
	.byte	0x20
	.byte	0x5
	.ascii	"mapRenderOrigin\000"

	.byte	0xa
	.byte	0x52
	.4byte	0x17c0
	.byte	0x2
	.byte	0x23
	.byte	0x24
	.byte	0x5
	.ascii	"cameraMax\000"

	.byte	0xa
	.byte	0x53
	.4byte	0x179a
	.byte	0x2
	.byte	0x23
	.byte	0x28
	.byte	0x5
	.ascii	"um_tmp_item\000"

	.byte	0xa
	.byte	0x55
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x2c
	.byte	0x5
	.ascii	"itemUnk2E\000"

	.byte	0xa
	.byte	0x56
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x2e
	.byte	0x5
	.ascii	"unk30\000"

	.byte	0xa
	.byte	0x58
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x30
	.byte	0x5
	.ascii	"unk32\000"

	.byte	0xa
	.byte	0x59
	.4byte	0xbb2
	.byte	0x2
	.byte	0x23
	.byte	0x32
	.byte	0x5
	.ascii	"unk34\000"

	.byte	0xa
	.byte	0x5a
	.4byte	0xbb2
	.byte	0x2
	.byte	0x23
	.byte	0x34
	.byte	0x5
	.ascii	"unk36\000"

	.byte	0xa
	.byte	0x5b
	.4byte	0xba8
	.byte	0x2
	.byte	0x23
	.byte	0x36
	.byte	0x5
	.ascii	"unk37\000"

	.byte	0xa
	.byte	0x5c
	.4byte	0xba8
	.byte	0x2
	.byte	0x23
	.byte	0x37
	.byte	0x5
	.ascii	"altBlendACa\000"

	.byte	0xa
	.byte	0x5d
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x38
	.byte	0x5
	.ascii	"altBlendACb\000"

	.byte	0xa
	.byte	0x5e
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x39
	.byte	0x5
	.ascii	"altBlendBCa\000"

	.byte	0xa
	.byte	0x5f
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x3a
	.byte	0x5
	.ascii	"altBlendBCb\000"

	.byte	0xa
	.byte	0x60
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x3b
	.byte	0x5
	.ascii	"just_resumed\000"

	.byte	0xa
	.byte	0x61
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x3c
	.byte	0x5
	.ascii	"taken_action\000"

	.byte	0xa
	.byte	0x62
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x3d
	.byte	0x5
	.ascii	"swapActionRangeCount\000"

	.byte	0xa
	.byte	0x63
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x3e
	.byte	0x5
	.ascii	"unk3F\000"

	.byte	0xa
	.byte	0x64
	.4byte	0xba8
	.byte	0x2
	.byte	0x23
	.byte	0x3f
	.byte	0x0
	.byte	0x1a
	.4byte	0x1b2d
	.ascii	"BmSt_gameStateBits\000"

	.byte	0x4
	.byte	0xa
	.byte	0x67
	.byte	0x14
	.ascii	"BM_FLAG_0\000"

	.byte	0x1
	.byte	0x14
	.ascii	"BM_FLAG_1\000"

	.byte	0x2
	.byte	0x14
	.ascii	"BM_FLAG_2\000"

	.byte	0x4
	.byte	0x14
	.ascii	"BM_FLAG_3\000"

	.byte	0x8
	.byte	0x14
	.ascii	"BM_FLAG_PREPSCREEN\000"

	.byte	0x10
	.byte	0x14
	.ascii	"BM_FLAG_5\000"

	.byte	0x20
	.byte	0x14
	.ascii	"BM_FLAG_LINKARENA\000"

	.byte	0x40
	.byte	0x0
	.byte	0x1a
	.4byte	0x1baa
	.ascii	"BmSt_TakenAction\000"

	.byte	0x4
	.byte	0xa
	.byte	0x71
	.byte	0x14
	.ascii	"BM_TAKEN_ACTION_TAKE\000"

	.byte	0x1
	.byte	0x14
	.ascii	"BM_TAKEN_ACTION_TRADE\000"

	.byte	0x2
	.byte	0x14
	.ascii	"BM_TAKEN_ACTION_SUPPLY\000"

	.byte	0x4
	.byte	0x14
	.ascii	"BM_TAKEN_ACTION_BALLISTA\000"

	.byte	0x8
	.byte	0x0
	.byte	0x4
	.4byte	0x1cf7
	.ascii	"PlaySt_30\000"

	.byte	0x10
	.byte	0xa
	.byte	0x78
	.byte	0x5
	.ascii	"total_gold\000"

	.byte	0xa
	.byte	0x79
	.4byte	0xbbd
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"unk_4_00\000"

	.byte	0xa
	.byte	0x7b
	.4byte	0xb92
	.byte	0x4
	.byte	0x14
	.byte	0xc
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x16
	.ascii	"unk_4_14\000"

	.byte	0xa
	.byte	0x7c
	.4byte	0xb92
	.byte	0x4
	.byte	0xc
	.byte	0x0
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x16
	.ascii	"unk_8_1\000"

	.byte	0xa
	.byte	0x7e
	.4byte	0xb92
	.byte	0x4
	.byte	0x8
	.byte	0x18
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x16
	.ascii	"unk_8_2\000"

	.byte	0xa
	.byte	0x7f
	.4byte	0xb92
	.byte	0x4
	.byte	0x14
	.byte	0x4
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x16
	.ascii	"unk_8_3\000"

	.byte	0xa
	.byte	0x80
	.4byte	0xb92
	.byte	0x4
	.byte	0x4
	.byte	0x0
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x16
	.ascii	"unk_C_00\000"

	.byte	0xa
	.byte	0x82
	.4byte	0xb92
	.byte	0x4
	.byte	0x6
	.byte	0x1a
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x16
	.ascii	"combatRank\000"

	.byte	0xa
	.byte	0x83
	.4byte	0xb92
	.byte	0x4
	.byte	0x3
	.byte	0x17
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x16
	.ascii	"expRank\000"

	.byte	0xa
	.byte	0x84
	.4byte	0xb92
	.byte	0x4
	.byte	0x3
	.byte	0x14
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x16
	.ascii	"unk_3D_04\000"

	.byte	0xa
	.byte	0x85
	.4byte	0xb92
	.byte	0x4
	.byte	0x3
	.byte	0x11
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x16
	.ascii	"fundsRank\000"

	.byte	0xa
	.byte	0x86
	.4byte	0xb92
	.byte	0x4
	.byte	0x3
	.byte	0xe
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x16
	.ascii	"tacticsRank\000"

	.byte	0xa
	.byte	0x87
	.4byte	0xb92
	.byte	0x4
	.byte	0x3
	.byte	0xb
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x16
	.ascii	"survivalRank\000"

	.byte	0xa
	.byte	0x88
	.4byte	0xb92
	.byte	0x4
	.byte	0x3
	.byte	0x8
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x16
	.ascii	"unk_F_00\000"

	.byte	0xa
	.byte	0x89
	.4byte	0xb92
	.byte	0x4
	.byte	0x8
	.byte	0x0
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x0
	.byte	0x4
	.4byte	0x1f55
	.ascii	"PlaySt_OptionBits\000"

	.byte	0x8
	.byte	0xa
	.byte	0x8c
	.byte	0x16
	.ascii	"unitColor\000"

	.byte	0xa
	.byte	0x8e
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0x1f
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"disableTerrainDisplay\000"

	.byte	0xa
	.byte	0x8f
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0x1e
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"unitDisplayType\000"

	.byte	0xa
	.byte	0x90
	.4byte	0xb92
	.byte	0x4
	.byte	0x2
	.byte	0x1c
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"autoCursor\000"

	.byte	0xa
	.byte	0x91
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0x1b
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"textSpeed\000"

	.byte	0xa
	.byte	0x92
	.4byte	0xb92
	.byte	0x4
	.byte	0x2
	.byte	0x19
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"gameSpeed\000"

	.byte	0xa
	.byte	0x93
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0x18
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"disableBgm\000"

	.byte	0xa
	.byte	0x95
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0x17
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"disableSoundEffects\000"

	.byte	0xa
	.byte	0x96
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0x16
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"windowColor\000"

	.byte	0xa
	.byte	0x97
	.4byte	0xb92
	.byte	0x4
	.byte	0x2
	.byte	0x14
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"unk41_5\000"

	.byte	0xa
	.byte	0x98
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0x13
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"unk41_6\000"

	.byte	0xa
	.byte	0x99
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0x12
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"disableAutoEndTurns\000"

	.byte	0xa
	.byte	0x9a
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0x11
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"noSubtitleHelp\000"

	.byte	0xa
	.byte	0x9b
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0x10
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"disableGoalDisplay\000"

	.byte	0xa
	.byte	0x9d
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0xf
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"animationType\000"

	.byte	0xa
	.byte	0x9e
	.4byte	0xb92
	.byte	0x4
	.byte	0x2
	.byte	0xd
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"battleForecastType\000"

	.byte	0xa
	.byte	0x9f
	.4byte	0xb92
	.byte	0x4
	.byte	0x2
	.byte	0xb
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"controller\000"

	.byte	0xa
	.byte	0xa0
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0xa
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"rankDisplay\000"

	.byte	0xa
	.byte	0xa1
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0x9
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"debugControlRed\000"

	.byte	0xa
	.byte	0xa3
	.4byte	0xb92
	.byte	0x4
	.byte	0x2
	.byte	0x7
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"debugControlGreen\000"

	.byte	0xa
	.byte	0xa4
	.4byte	0xb92
	.byte	0x4
	.byte	0x2
	.byte	0x5
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x16
	.ascii	"unk43_4\000"

	.byte	0xa
	.byte	0xa5
	.4byte	0xb92
	.byte	0x4
	.byte	0x5
	.byte	0x0
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"unk44\000"

	.byte	0xa
	.byte	0xa7
	.4byte	0x1776
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x0
	.byte	0x4
	.4byte	0x22a6
	.ascii	"PlaySt\000"

	.byte	0x4c
	.byte	0xa
	.byte	0xaa
	.byte	0x5
	.ascii	"time_saved\000"

	.byte	0xa
	.byte	0xab
	.4byte	0xb92
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"time_chapter_started\000"

	.byte	0xa
	.byte	0xac
	.4byte	0xb92
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x5
	.ascii	"partyGoldAmount\000"

	.byte	0xa
	.byte	0xae
	.4byte	0xb92
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x5
	.ascii	"gameSaveSlot\000"

	.byte	0xa
	.byte	0xaf
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x5
	.ascii	"chapterVisionRange\000"

	.byte	0xa
	.byte	0xb1
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0xd
	.byte	0x5
	.ascii	"chapterIndex\000"

	.byte	0xa
	.byte	0xb2
	.4byte	0xba8
	.byte	0x2
	.byte	0x23
	.byte	0xe
	.byte	0x5
	.ascii	"faction\000"

	.byte	0xa
	.byte	0xb4
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0xf
	.byte	0x5
	.ascii	"chapterTurnNumber\000"

	.byte	0xa
	.byte	0xb6
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x10
	.byte	0x5
	.ascii	"xCursor\000"

	.byte	0xa
	.byte	0xb8
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x12
	.byte	0x5
	.ascii	"yCursor\000"

	.byte	0xa
	.byte	0xb8
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x13
	.byte	0x5
	.ascii	"chapterStateBits\000"

	.byte	0xa
	.byte	0xba
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x14
	.byte	0x5
	.ascii	"chapterWeatherId\000"

	.byte	0xa
	.byte	0xbb
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x15
	.byte	0x5
	.ascii	"chapterTotalSupportGain\000"

	.byte	0xa
	.byte	0xbc
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x16
	.byte	0x5
	.ascii	"playthroughIdentifier\000"

	.byte	0xa
	.byte	0xbe
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x18
	.byte	0x5
	.ascii	"unk19\000"

	.byte	0xa
	.byte	0xbf
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x19
	.byte	0x5
	.ascii	"lastUnitSortType\000"

	.byte	0xa
	.byte	0xc0
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x1a
	.byte	0x5
	.ascii	"chapterModeIndex\000"

	.byte	0xa
	.byte	0xc2
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x1b
	.byte	0x5
	.ascii	"unk1C\000"

	.byte	0xa
	.byte	0xc6
	.4byte	0x22a6
	.byte	0x2
	.byte	0x23
	.byte	0x1c
	.byte	0x5
	.ascii	"unk1E\000"

	.byte	0xa
	.byte	0xc7
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x1e
	.byte	0x5
	.ascii	"unk1F\000"

	.byte	0xa
	.byte	0xc8
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x1f
	.byte	0x5
	.ascii	"playerName\000"

	.byte	0xa
	.byte	0xca
	.4byte	0x22b2
	.byte	0x2
	.byte	0x23
	.byte	0x20
	.byte	0x16
	.ascii	"unk_2B_00\000"

	.byte	0xa
	.byte	0xcc
	.4byte	0xb7d
	.byte	0x1
	.byte	0x1
	.byte	0x7
	.byte	0x2
	.byte	0x23
	.byte	0x2b
	.byte	0x16
	.ascii	"unk_2B_01\000"

	.byte	0xa
	.byte	0xcd
	.4byte	0xb7d
	.byte	0x1
	.byte	0x7
	.byte	0x0
	.byte	0x2
	.byte	0x23
	.byte	0x2b
	.byte	0x16
	.ascii	"unk_2C_1\000"

	.byte	0xa
	.byte	0xcf
	.4byte	0xb92
	.byte	0x4
	.byte	0x1
	.byte	0x1f
	.byte	0x2
	.byte	0x23
	.byte	0x2c
	.byte	0x16
	.ascii	"unk_2C_01\000"

	.byte	0xa
	.byte	0xd0
	.4byte	0xb92
	.byte	0x4
	.byte	0x3
	.byte	0x1c
	.byte	0x2
	.byte	0x23
	.byte	0x2c
	.byte	0x16
	.ascii	"unk_2C_04\000"

	.byte	0xa
	.byte	0xd1
	.4byte	0xb92
	.byte	0x4
	.byte	0x9
	.byte	0x13
	.byte	0x2
	.byte	0x23
	.byte	0x2c
	.byte	0x16
	.ascii	"unk_2C_0D\000"

	.byte	0xa
	.byte	0xd2
	.4byte	0xb92
	.byte	0x4
	.byte	0xa
	.byte	0x9
	.byte	0x2
	.byte	0x23
	.byte	0x2c
	.byte	0x16
	.ascii	"unk_2C_2\000"

	.byte	0xa
	.byte	0xd3
	.4byte	0xb92
	.byte	0x4
	.byte	0x5
	.byte	0x4
	.byte	0x2
	.byte	0x23
	.byte	0x2c
	.byte	0x16
	.ascii	"unk_2C_3\000"

	.byte	0xa
	.byte	0xd4
	.4byte	0xb92
	.byte	0x4
	.byte	0x4
	.byte	0x0
	.byte	0x2
	.byte	0x23
	.byte	0x2c
	.byte	0x5
	.ascii	"unk_30\000"

	.byte	0xa
	.byte	0xd6
	.4byte	0x1baa
	.byte	0x2
	.byte	0x23
	.byte	0x30
	.byte	0x5
	.ascii	"config\000"

	.byte	0xa
	.byte	0xd8
	.4byte	0x1cf7
	.byte	0x2
	.byte	0x23
	.byte	0x40
	.byte	0x5
	.ascii	"unk48\000"

	.byte	0xa
	.byte	0xda
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x48
	.byte	0x16
	.ascii	"unk4A_1\000"

	.byte	0xa
	.byte	0xdc
	.4byte	0xb7d
	.byte	0x1
	.byte	0x1
	.byte	0x7
	.byte	0x2
	.byte	0x23
	.byte	0x4a
	.byte	0x16
	.ascii	"save_menu_type\000"

	.byte	0xa
	.byte	0xdd
	.4byte	0xb7d
	.byte	0x1
	.byte	0x3
	.byte	0x4
	.byte	0x2
	.byte	0x23
	.byte	0x4a
	.byte	0x16
	.ascii	"tutorial_exec_type\000"

	.byte	0xa
	.byte	0xde
	.4byte	0xb7d
	.byte	0x1
	.byte	0x4
	.byte	0x0
	.byte	0x2
	.byte	0x23
	.byte	0x4a
	.byte	0x5
	.ascii	"tutorial_counter\000"

	.byte	0xa
	.byte	0xdf
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x4b
	.byte	0x0
	.byte	0xb
	.4byte	0x22b2
	.4byte	0xb7d
	.byte	0xc
	.byte	0x1
	.byte	0x0
	.byte	0xb
	.4byte	0x22be
	.4byte	0x3ed
	.byte	0xc
	.byte	0xa
	.byte	0x0
	.byte	0x1a
	.4byte	0x2339
	.ascii	"PlaySt_AnimConfType\000"

	.byte	0x4
	.byte	0xa
	.byte	0xe3
	.byte	0x14
	.ascii	"PLAY_ANIMCONF_ON\000"

	.byte	0x0
	.byte	0x14
	.ascii	"PLAY_ANIMCONF_OFF\000"

	.byte	0x1
	.byte	0x14
	.ascii	"PLAY_ANIMCONF_SOLO_ANIM\000"

	.byte	0x2
	.byte	0x14
	.ascii	"PLAY_ANIMCONF_ON_UNIQUE_BG\000"

	.byte	0x3
	.byte	0x0
	.byte	0x1a
	.4byte	0x2450
	.ascii	"PlaySt_chapterStateBits\000"

	.byte	0x4
	.byte	0xa
	.byte	0xee
	.byte	0x14
	.ascii	"PLAY_FLAG_STATSCREENPAGE0\000"

	.byte	0x1
	.byte	0x14
	.ascii	"PLAY_FLAG_STATSCREENPAGE1\000"

	.byte	0x2
	.byte	0x14
	.ascii	"PLAY_FLAG_POSTGAME\000"

	.byte	0x4
	.byte	0x14
	.ascii	"PLAY_FLAG_TUTORIAL\000"

	.byte	0x8
	.byte	0x14
	.ascii	"PLAY_FLAG_PREPSCREEN\000"

	.byte	0x10
	.byte	0x14
	.ascii	"PLAY_FLAG_COMPLETE\000"

	.byte	0x20
	.byte	0x14
	.ascii	"PLAY_FLAG_HARD\000"

	.byte	0x40
	.byte	0x14
	.ascii	"PLAY_FLAG_EXTRA_MAP\000"

	.byte	0x80
	.byte	0x14
	.ascii	"PLAY_FLAG_STATSCREENPAGE_SHIFT\000"

	.byte	0x0
	.byte	0x14
	.ascii	"PLAY_FLAG_STATSCREENPAGE_MASK\000"

	.byte	0x3
	.byte	0x0
	.byte	0x1c
	.4byte	0x24c8
	.ascii	"PlaySt_chapterModeIndex\000"

	.byte	0x4
	.byte	0xa
	.2byte	0x100
	.byte	0x14
	.ascii	"CHAPTER_MODE_COMMON\000"

	.byte	0x1
	.byte	0x14
	.ascii	"CHAPTER_MODE_EIRIKA\000"

	.byte	0x2
	.byte	0x14
	.ascii	"CHAPTER_MODE_EPHRAIM\000"

	.byte	0x3
	.byte	0x14
	.ascii	"CHAPTER_MODE_ANY\000"

	.byte	0xff
	.byte	0x0
	.byte	0x1d
	.4byte	0x2540
	.ascii	"MsgBuffer\000"

	.2byte	0x1000
	.byte	0xa
	.2byte	0x109
	.byte	0x1e
	.ascii	"buffer1\000"

	.byte	0xa
	.2byte	0x10a
	.4byte	0x2540
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x1e
	.ascii	"buffer2\000"

	.byte	0xa
	.2byte	0x10b
	.4byte	0x2540
	.byte	0x3
	.byte	0x23
	.byte	0xd5,0xa
	.byte	0x1e
	.ascii	"buffer3\000"

	.byte	0xa
	.2byte	0x10c
	.4byte	0x254d
	.byte	0x3
	.byte	0x23
	.byte	0xaa,0x15
	.byte	0x1e
	.ascii	"buffer4\000"

	.byte	0xa
	.2byte	0x10d
	.4byte	0x255a
	.byte	0x3
	.byte	0x23
	.byte	0x80,0x1c
	.byte	0x1e
	.ascii	"buffer5\000"

	.byte	0xa
	.2byte	0x10e
	.4byte	0x255a
	.byte	0x3
	.byte	0x23
	.byte	0x80,0x1e
	.byte	0x0
	.byte	0xb
	.4byte	0x254d
	.4byte	0xb7d
	.byte	0x1f
	.2byte	0x554
	.byte	0x0
	.byte	0xb
	.4byte	0x255a
	.4byte	0xb7d
	.byte	0x1f
	.2byte	0x355
	.byte	0x0
	.byte	0xb
	.4byte	0x2566
	.4byte	0xb7d
	.byte	0xc
	.byte	0xff
	.byte	0x0
	.byte	0x13
	.4byte	0x25a7
	.byte	0x4
	.byte	0xa
	.2byte	0x112
	.byte	0x14
	.ascii	"FACING_LEFT\000"

	.byte	0x0
	.byte	0x14
	.ascii	"FACING_RIGHT\000"

	.byte	0x1
	.byte	0x14
	.ascii	"FACING_DOWN\000"

	.byte	0x2
	.byte	0x14
	.ascii	"FACING_UP\000"

	.byte	0x3
	.byte	0x0
	.byte	0x13
	.4byte	0x2834
	.byte	0x4
	.byte	0xa
	.2byte	0x11a
	.byte	0x14
	.ascii	"UNIT_ACTION_WAIT\000"

	.byte	0x1
	.byte	0x14
	.ascii	"UNIT_ACTION_COMBAT\000"

	.byte	0x2
	.byte	0x14
	.ascii	"UNIT_ACTION_STAFF\000"

	.byte	0x3
	.byte	0x14
	.ascii	"UNIT_ACTION_DANCE\000"

	.byte	0x4
	.byte	0x14
	.ascii	"UNIT_ACTION_UNK05\000"

	.byte	0x5
	.byte	0x14
	.ascii	"UNIT_ACTION_STEAL\000"

	.byte	0x6
	.byte	0x14
	.ascii	"UNIT_ACTION_SUMMON\000"

	.byte	0x7
	.byte	0x14
	.ascii	"UNIT_ACTION_SUMMON_DK\000"

	.byte	0x8
	.byte	0x14
	.ascii	"UNIT_ACTION_RESCUE\000"

	.byte	0x9
	.byte	0x14
	.ascii	"UNIT_ACTION_DROP\000"

	.byte	0xa
	.byte	0x14
	.ascii	"UNIT_ACTION_TAKE\000"

	.byte	0xb
	.byte	0x14
	.ascii	"UNIT_ACTION_GIVE\000"

	.byte	0xc
	.byte	0x14
	.ascii	"UNIT_ACTION_UNK0D\000"

	.byte	0xd
	.byte	0x14
	.ascii	"UNIT_ACTION_TALK\000"

	.byte	0xe
	.byte	0x14
	.ascii	"UNIT_ACTION_SUPPORT\000"

	.byte	0xf
	.byte	0x14
	.ascii	"UNIT_ACTION_VISIT\000"

	.byte	0x10
	.byte	0x14
	.ascii	"UNIT_ACTION_SEIZE\000"

	.byte	0x11
	.byte	0x14
	.ascii	"UNIT_ACTION_DOOR\000"

	.byte	0x12
	.byte	0x14
	.ascii	"UNIT_ACTION_CHEST\000"

	.byte	0x14
	.byte	0x14
	.ascii	"UNIT_ACTION_PICK\000"

	.byte	0x15
	.byte	0x14
	.ascii	"UNIT_ACTION_SHOPPED\000"

	.byte	0x17
	.byte	0x14
	.ascii	"UNIT_ACTION_ARENA\000"

	.byte	0x19
	.byte	0x14
	.ascii	"UNIT_ACTION_USE_ITEM\000"

	.byte	0x1a
	.byte	0x14
	.ascii	"UNIT_ACTION_TRADED\000"

	.byte	0x1b
	.byte	0x14
	.ascii	"UNIT_ACTION_TRADED_SUPPLY\000"

	.byte	0x1c
	.byte	0x14
	.ascii	"UNIT_ACTION_TRADED_1D\000"

	.byte	0x1d
	.byte	0x14
	.ascii	"UNIT_ACTION_TRAPPED\000"

	.byte	0x1e
	.byte	0x14
	.ascii	"UNIT_ACTION_FORCE_WAIT\000"

	.byte	0x1f
	.byte	0x14
	.ascii	"UNIT_ACTION_RIDE_BALLISTA\000"

	.byte	0x21
	.byte	0x14
	.ascii	"UNIT_ACTION_EXIT_BALLISTA\000"

	.byte	0x22
	.byte	0x0
	.byte	0x13
	.4byte	0x2927
	.byte	0x4
	.byte	0xa
	.2byte	0x141
	.byte	0x14
	.ascii	"SUSPEND_POINT_PLAYERIDLE\000"

	.byte	0x0
	.byte	0x14
	.ascii	"SUSPEND_POINT_DURINGACTION\000"

	.byte	0x1
	.byte	0x14
	.ascii	"SUSPEND_POINT_CPPHASE\000"

	.byte	0x2
	.byte	0x14
	.ascii	"SUSPEND_POINT_BSKPHASE\000"

	.byte	0x3
	.byte	0x14
	.ascii	"SUSPEND_POINT_DURINGARENA\000"

	.byte	0x4
	.byte	0x14
	.ascii	"SUSPEND_POINT_5\000"

	.byte	0x5
	.byte	0x14
	.ascii	"SUSPEND_POINT_6\000"

	.byte	0x6
	.byte	0x14
	.ascii	"SUSPEND_POINT_7\000"

	.byte	0x7
	.byte	0x14
	.ascii	"SUSPEND_POINT_8\000"

	.byte	0x8
	.byte	0x14
	.ascii	"SUSPEND_POINT_PHASECHANGE\000"

	.byte	0x9
	.byte	0x0
	.byte	0x13
	.4byte	0x2a34
	.byte	0x4
	.byte	0xa
	.2byte	0x14f
	.byte	0x14
	.ascii	"GAME_ACTION_EVENT_RETURN\000"

	.byte	0x0
	.byte	0x14
	.ascii	"GAME_ACTION_CLASS_REEL\000"

	.byte	0x1
	.byte	0x14
	.ascii	"GAME_ACTION_USR_SKIPPED\000"

	.byte	0x2
	.byte	0x14
	.ascii	"GAME_ACTION_PLAYED_THROUGH\000"

	.byte	0x3
	.byte	0x14
	.ascii	"GAME_ACTION_4\000"

	.byte	0x4
	.byte	0x14
	.ascii	"GAME_ACTION_5\000"

	.byte	0x5
	.byte	0x14
	.ascii	"GAME_ACTION_6\000"

	.byte	0x6
	.byte	0x14
	.ascii	"GAME_ACTION_EXTRA_MAP\000"

	.byte	0x7
	.byte	0x14
	.ascii	"GAME_ACTION_8\000"

	.byte	0x8
	.byte	0x14
	.ascii	"GAME_ACTION_9\000"

	.byte	0x9
	.byte	0x14
	.ascii	"GAME_ACTION_A\000"

	.byte	0xa
	.byte	0x14
	.ascii	"GAME_ACTION_B\000"

	.byte	0xb
	.byte	0x14
	.ascii	"GAME_ACTION_C\000"

	.byte	0xc
	.byte	0x0
	.byte	0x13
	.4byte	0x2ac5
	.byte	0x4
	.byte	0xa
	.2byte	0x160
	.byte	0x14
	.ascii	"WEATHER_FINE\000"

	.byte	0x0
	.byte	0x14
	.ascii	"WEATHER_SNOW\000"

	.byte	0x1
	.byte	0x14
	.ascii	"WEATHER_SNOWSTORM\000"

	.byte	0x2
	.byte	0x14
	.ascii	"WEATHER_NIGHT\000"

	.byte	0x3
	.byte	0x14
	.ascii	"WEATHER_RAIN\000"

	.byte	0x4
	.byte	0x14
	.ascii	"WEATHER_FLAMES\000"

	.byte	0x5
	.byte	0x14
	.ascii	"WEATHER_SANDSTORM\000"

	.byte	0x6
	.byte	0x14
	.ascii	"WEATHER_CLOUDS\000"

	.byte	0x7
	.byte	0x0
	.byte	0x13
	.4byte	0x2b19
	.byte	0x4
	.byte	0xa
	.2byte	0x16c
	.byte	0x14
	.ascii	"BATTLEMAP_KIND_STORY\000"

	.byte	0x0
	.byte	0x14
	.ascii	"BATTLEMAP_KIND_DUNGEON\000"

	.byte	0x1
	.byte	0x14
	.ascii	"BATTLEMAP_KIND_SKIRMISH\000"

	.byte	0x2
	.byte	0x0
	.byte	0x13
	.4byte	0x2b8c
	.byte	0x4
	.byte	0xa
	.2byte	0x173
	.byte	0x14
	.ascii	"GOAL_TYPE_SEIZE\000"

	.byte	0x0
	.byte	0x14
	.ascii	"GOAL_TYPE_DEFEAT_ALL\000"

	.byte	0x1
	.byte	0x14
	.ascii	"GOAL_TYPE_DEFENSE\000"

	.byte	0x2
	.byte	0x14
	.ascii	"GOAL_TYPE_DEFEAT_BOSS\000"

	.byte	0x3
	.byte	0x14
	.ascii	"GOAL_TYPE_SPECIAL\000"

	.byte	0x4
	.byte	0x0
	.byte	0x20
	.4byte	0x2c0f
	.ascii	"SMSHandle\000"

	.byte	0xc
	.byte	0xa
	.2byte	0x17c
	.byte	0x1e
	.ascii	"pNext\000"

	.byte	0xa
	.2byte	0x17d
	.4byte	0x2c0f
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x1e
	.ascii	"xDisplay\000"

	.byte	0xa
	.2byte	0x17f
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x1e
	.ascii	"yDisplay\000"

	.byte	0xa
	.2byte	0x180
	.4byte	0x38e
	.byte	0x2
	.byte	0x23
	.byte	0x6
	.byte	0x1e
	.ascii	"oam2Base\000"

	.byte	0xa
	.2byte	0x182
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x1e
	.ascii	"_u0A\000"

	.byte	0xa
	.2byte	0x184
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0xa
	.byte	0x1e
	.ascii	"config\000"

	.byte	0xa
	.2byte	0x185
	.4byte	0xba8
	.byte	0x2
	.byte	0x23
	.byte	0xb
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x2b8c
	.byte	0x20
	.4byte	0x2c8f
	.ascii	"MapChange\000"

	.byte	0xc
	.byte	0xa
	.2byte	0x189
	.byte	0x1e
	.ascii	"id\000"

	.byte	0xa
	.2byte	0x18a
	.4byte	0xba8
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x1e
	.ascii	"xOrigin\000"

	.byte	0xa
	.2byte	0x18b
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x1
	.byte	0x1e
	.ascii	"yOrigin\000"

	.byte	0xa
	.2byte	0x18c
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x2
	.byte	0x1e
	.ascii	"xSize\000"

	.byte	0xa
	.2byte	0x18d
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x3
	.byte	0x1e
	.ascii	"ySize\000"

	.byte	0xa
	.2byte	0x18e
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x1e
	.ascii	"data\000"

	.byte	0xa
	.2byte	0x18f
	.4byte	0x1644
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x0
	.byte	0x13
	.4byte	0x2cb2
	.byte	0x4
	.byte	0xa
	.2byte	0x192
	.byte	0x14
	.ascii	"UNIT_SUPPORT_MAX_COUNT\000"

	.byte	0x7
	.byte	0x0
	.byte	0x13
	.4byte	0x2ce4
	.byte	0x4
	.byte	0xa
	.2byte	0x195
	.byte	0x14
	.ascii	"FACE_BLINK_NORMAL\000"

	.byte	0x1
	.byte	0x14
	.ascii	"FACE_BLINK_CLOSED\000"

	.byte	0x6
	.byte	0x0
	.byte	0x20
	.4byte	0x2dab
	.ascii	"FaceData\000"

	.byte	0x1c
	.byte	0xa
	.2byte	0x19b
	.byte	0x1e
	.ascii	"img\000"

	.byte	0xa
	.2byte	0x19c
	.4byte	0x132b
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x1e
	.ascii	"imgChibi\000"

	.byte	0xa
	.2byte	0x19d
	.4byte	0x132b
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x1e
	.ascii	"pal\000"

	.byte	0xa
	.2byte	0x19e
	.4byte	0x2dab
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x1e
	.ascii	"imgMouth\000"

	.byte	0xa
	.2byte	0x19f
	.4byte	0x132b
	.byte	0x2
	.byte	0x23
	.byte	0xc
	.byte	0x1e
	.ascii	"imgCard\000"

	.byte	0xa
	.2byte	0x1a0
	.4byte	0x132b
	.byte	0x2
	.byte	0x23
	.byte	0x10
	.byte	0x1e
	.ascii	"xMouth\000"

	.byte	0xa
	.2byte	0x1a1
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x14
	.byte	0x1e
	.ascii	"yMouth\000"

	.byte	0xa
	.2byte	0x1a1
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x15
	.byte	0x1e
	.ascii	"xEyes\000"

	.byte	0xa
	.2byte	0x1a2
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x16
	.byte	0x1e
	.ascii	"yEyes\000"

	.byte	0xa
	.2byte	0x1a2
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x17
	.byte	0x1e
	.ascii	"blinkKind\000"

	.byte	0xa
	.2byte	0x1a3
	.4byte	0xb7d
	.byte	0x2
	.byte	0x23
	.byte	0x18
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x2db1
	.byte	0xa
	.4byte	0xb87
	.byte	0x20
	.4byte	0x2df9
	.ascii	"FaceVramEntry\000"

	.byte	0x8
	.byte	0xa
	.2byte	0x1a7
	.byte	0x1e
	.ascii	"tileOffset\000"

	.byte	0xa
	.2byte	0x1a8
	.4byte	0xb92
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x1e
	.ascii	"paletteId\000"

	.byte	0xa
	.2byte	0x1a9
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x0
	.byte	0x20
	.4byte	0x2e7c
	.ascii	"Struct202B6B0\000"

	.byte	0x8c
	.byte	0xa
	.2byte	0x1ac
	.byte	0x1e
	.ascii	"_pad00_\000"

	.byte	0xa
	.2byte	0x1ad
	.4byte	0x2e7c
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x1e
	.ascii	"unk2A\000"

	.byte	0xa
	.2byte	0x1ae
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x2a
	.byte	0x1e
	.ascii	"_pad2C\000"

	.byte	0xa
	.2byte	0x1af
	.4byte	0x2e88
	.byte	0x2
	.byte	0x23
	.byte	0x2c
	.byte	0x1e
	.ascii	"unk5A\000"

	.byte	0xa
	.2byte	0x1b0
	.4byte	0xb87
	.byte	0x2
	.byte	0x23
	.byte	0x5a
	.byte	0x1e
	.ascii	"_pad5C\000"

	.byte	0xa
	.2byte	0x1b1
	.4byte	0x2e88
	.byte	0x2
	.byte	0x23
	.byte	0x5c
	.byte	0x1e
	.ascii	"unk8A\000"

	.byte	0xa
	.2byte	0x1b2
	.4byte	0xb87
	.byte	0x3
	.byte	0x23
	.byte	0x8a,0x1
	.byte	0x0
	.byte	0xb
	.4byte	0x2e88
	.4byte	0xb7d
	.byte	0xc
	.byte	0x29
	.byte	0x0
	.byte	0xb
	.4byte	0x2e94
	.4byte	0xb7d
	.byte	0xc
	.byte	0x2d
	.byte	0x0
	.byte	0x20
	.4byte	0x2ed2
	.ascii	"EfxFrameConfig\000"

	.byte	0x4
	.byte	0xa
	.2byte	0x1b5
	.byte	0x1e
	.ascii	"value\000"

	.byte	0xa
	.2byte	0x1b6
	.4byte	0xbb2
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x1e
	.ascii	"duration\000"

	.byte	0xa
	.2byte	0x1b7
	.4byte	0xbb2
	.byte	0x2
	.byte	0x23
	.byte	0x2
	.byte	0x0
	.byte	0x20
	.4byte	0x2f11
	.ascii	"gfx_set\000"

	.byte	0xc
	.byte	0xa
	.2byte	0x1ba
	.byte	0x1e
	.ascii	"gfx\000"

	.byte	0xa
	.2byte	0x1bb
	.4byte	0x3cb
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x1e
	.ascii	"tsa\000"

	.byte	0xa
	.2byte	0x1bc
	.4byte	0x3cb
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x1e
	.ascii	"pal\000"

	.byte	0xa
	.2byte	0x1bd
	.4byte	0x3cb
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x0
	.byte	0x2
	.ascii	"ProcPtr\000"

	.byte	0xb
	.byte	0x6
	.4byte	0x3cb
	.byte	0x2
	.ascii	"ProcFunc\000"

	.byte	0xb
	.byte	0x7
	.4byte	0x2f30
	.byte	0x6
	.byte	0x4
	.4byte	0x1624
	.byte	0x4
	.4byte	0x2f80
	.ascii	"ProcFindIterator\000"

	.byte	0xc
	.byte	0xb
	.byte	0x61
	.byte	0x5
	.ascii	"proc\000"

	.byte	0xb
	.byte	0x62
	.4byte	0x2f80
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"script\000"

	.byte	0xb
	.byte	0x63
	.4byte	0x1619
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x5
	.ascii	"count\000"

	.byte	0xb
	.byte	0x64
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x0
	.byte	0x6
	.byte	0x4
	.4byte	0x1378
	.byte	0x17
	.4byte	0x3086
	.byte	0x4
	.byte	0xb
	.byte	0x68
	.byte	0x14
	.ascii	"PROC_MARK_0\000"

	.byte	0x0
	.byte	0x14
	.ascii	"PROC_MARK_DISP\000"

	.byte	0x1
	.byte	0x14
	.ascii	"PROC_MARK_MAIN\000"

	.byte	0x2
	.byte	0x14
	.ascii	"PROC_MARK_3\000"

	.byte	0x3
	.byte	0x14
	.ascii	"PROC_MARK_MU\000"

	.byte	0x4
	.byte	0x14
	.ascii	"PROC_MARK_TALK\000"

	.byte	0x5
	.byte	0x14
	.ascii	"PROC_MARK_EVENT\000"

	.byte	0x6
	.byte	0x14
	.ascii	"PROC_MARK_EVENT_ANIM\000"

	.byte	0x7
	.byte	0x14
	.ascii	"PROC_MARK_WMSTUFF\000"

	.byte	0x8
	.byte	0x14
	.ascii	"PROC_MARK_9\000"

	.byte	0x9
	.byte	0x14
	.ascii	"PROC_MARK_EFX_BGCOL\000"

	.byte	0xa
	.byte	0x14
	.ascii	"PROC_MARK_GAMECTRL\000"

	.byte	0xb
	.byte	0x14
	.ascii	"PROC_MARK_SAVEDRAW\000"

	.byte	0xc
	.byte	0x14
	.ascii	"PROC_MARK_D\000"

	.byte	0xd
	.byte	0x0
	.byte	0x19
	.ascii	"Font\000"

	.byte	0x1
	.byte	0x19
	.ascii	"GMapData\000"

	.byte	0x1
	.byte	0x19
	.ascii	"MusicPlayerInfo\000"

	.byte	0x1
	.byte	0x19
	.ascii	"BgCnt\000"

	.byte	0x1
	.byte	0x19
	.ascii	"Glyph\000"

	.byte	0x1
	.byte	0x20
	.4byte	0x30ef
	.ascii	"Unknown_08A209FC\000"

	.byte	0x4
	.byte	0xc
	.2byte	0x379
	.byte	0x1e
	.ascii	"a\000"

	.byte	0xc
	.2byte	0x37a
	.4byte	0xba8
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x1e
	.ascii	"b\000"

	.byte	0xc
	.2byte	0x37b
	.4byte	0xba8
	.byte	0x2
	.byte	0x23
	.byte	0x1
	.byte	0x0
	.byte	0x17
	.4byte	0x3882
	.byte	0x4
	.byte	0xd
	.byte	0x4
	.byte	0x14
	.ascii	"CHARACTER_NONE\000"

	.byte	0x0
	.byte	0x14
	.ascii	"CHARACTER_EIRIKA\000"

	.byte	0x1
	.byte	0x14
	.ascii	"CHARACTER_SETH\000"

	.byte	0x2
	.byte	0x14
	.ascii	"CHARACTER_GILLIAM\000"

	.byte	0x3
	.byte	0x14
	.ascii	"CHARACTER_FRANZ\000"

	.byte	0x4
	.byte	0x14
	.ascii	"CHARACTER_MOULDER\000"

	.byte	0x5
	.byte	0x14
	.ascii	"CHARACTER_VANESSA\000"

	.byte	0x6
	.byte	0x14
	.ascii	"CHARACTER_ROSS\000"

	.byte	0x7
	.byte	0x14
	.ascii	"CHARACTER_NEIMI\000"

	.byte	0x8
	.byte	0x14
	.ascii	"CHARACTER_COLM\000"

	.byte	0x9
	.byte	0x14
	.ascii	"CHARACTER_GARCIA\000"

	.byte	0xa
	.byte	0x14
	.ascii	"CHARACTER_INNES\000"

	.byte	0xb
	.byte	0x14
	.ascii	"CHARACTER_LUTE\000"

	.byte	0xc
	.byte	0x14
	.ascii	"CHARACTER_NATASHA\000"

	.byte	0xd
	.byte	0x14
	.ascii	"CHARACTER_CORMAG\000"

	.byte	0xe
	.byte	0x14
	.ascii	"CHARACTER_EPHRAIM\000"

	.byte	0xf
	.byte	0x14
	.ascii	"CHARACTER_FORDE\000"

	.byte	0x10
	.byte	0x14
	.ascii	"CHARACTER_KYLE\000"

	.byte	0x11
	.byte	0x14
	.ascii	"CHARACTER_AMELIA\000"

	.byte	0x12
	.byte	0x14
	.ascii	"CHARACTER_ARTUR\000"

	.byte	0x13
	.byte	0x14
	.ascii	"CHARACTER_GERIK\000"

	.byte	0x14
	.byte	0x14
	.ascii	"CHARACTER_TETHYS\000"

	.byte	0x15
	.byte	0x14
	.ascii	"CHARACTER_MARISA\000"

	.byte	0x16
	.byte	0x14
	.ascii	"CHARACTER_SALEH\000"

	.byte	0x17
	.byte	0x14
	.ascii	"CHARACTER_EWAN\000"

	.byte	0x18
	.byte	0x14
	.ascii	"CHARACTER_LARACHEL\000"

	.byte	0x19
	.byte	0x14
	.ascii	"CHARACTER_DOZLA\000"

	.byte	0x1a
	.byte	0x14
	.ascii	"CHARACTER_RENNAC\000"

	.byte	0x1c
	.byte	0x14
	.ascii	"CHARACTER_DUESSEL\000"

	.byte	0x1d
	.byte	0x14
	.ascii	"CHARACTER_MYRRH\000"

	.byte	0x1e
	.byte	0x14
	.ascii	"CHARACTER_KNOLL\000"

	.byte	0x1f
	.byte	0x14
	.ascii	"CHARACTER_JOSHUA\000"

	.byte	0x20
	.byte	0x14
	.ascii	"CHARACTER_SYRENE\000"

	.byte	0x21
	.byte	0x14
	.ascii	"CHARACTER_TANA\000"

	.byte	0x22
	.byte	0x14
	.ascii	"CHARACTER_LYON_CC\000"

	.byte	0x23
	.byte	0x14
	.ascii	"CHARACTER_ORSON_CC\000"

	.byte	0x24
	.byte	0x14
	.ascii	"CHARACTER_GLEN_CC\000"

	.byte	0x25
	.byte	0x14
	.ascii	"CHARACTER_SELENA_CC\000"

	.byte	0x26
	.byte	0x14
	.ascii	"CHARACTER_VALTER_CC\000"

	.byte	0x27
	.byte	0x14
	.ascii	"CHARACTER_RIEV_CC\000"

	.byte	0x28
	.byte	0x14
	.ascii	"CHARACTER_CAELLACH_CC\000"

	.byte	0x29
	.byte	0x14
	.ascii	"CHARACTER_FADO_CC\000"

	.byte	0x2a
	.byte	0x14
	.ascii	"CHARACTER_ISMAIRE_CC\000"

	.byte	0x2b
	.byte	0x14
	.ascii	"CHARACTER_HAYDEN_CC\000"

	.byte	0x2c
	.byte	0x14
	.ascii	"CHARACTER_SUMMON_LYON\000"

	.byte	0x3b
	.byte	0x14
	.ascii	"CHARACTER_SUMMON_KNOLL\000"

	.byte	0x3e
	.byte	0x14
	.ascii	"CHARACTER_SUMMON_EWAN\000"

	.byte	0x3f
	.byte	0x14
	.ascii	"CHARACTER_LYON\000"

	.byte	0x40
	.byte	0x14
	.ascii	"CHARACTER_MORVA\000"

	.byte	0x41
	.byte	0x14
	.ascii	"CHARACTER_ORSON_CH5X\000"

	.byte	0x42
	.byte	0x14
	.ascii	"CHARACTER_VALTER\000"

	.byte	0x43
	.byte	0x14
	.ascii	"CHARACTER_SELENA\000"

	.byte	0x44
	.byte	0x14
	.ascii	"CHARACTER_VALTER_PROLOGUE\000"

	.byte	0x45
	.byte	0x14
	.ascii	"CHARACTER_BREGUET\000"

	.byte	0x46
	.byte	0x14
	.ascii	"CHARACTER_BONE\000"

	.byte	0x47
	.byte	0x14
	.ascii	"CHARACTER_BAZBA\000"

	.byte	0x48
	.byte	0x14
	.ascii	"CHARACTER_ENTOUMBED_CH4\000"

	.byte	0x49
	.byte	0x14
	.ascii	"CHARACTER_SAAR\000"

	.byte	0x4a
	.byte	0x14
	.ascii	"CHARACTER_NOVALA\000"

	.byte	0x4b
	.byte	0x14
	.ascii	"CHARACTER_MURRAY\000"

	.byte	0x4c
	.byte	0x14
	.ascii	"CHARACTER_TIRADO\000"

	.byte	0x4d
	.byte	0x14
	.ascii	"CHARACTER_BINKS\000"

	.byte	0x4e
	.byte	0x14
	.ascii	"CHARACTER_PABLO\000"

	.byte	0x4f
	.byte	0x14
	.ascii	"CHARACTER_MAELDUIN_CHUnk\000"

	.byte	0x50
	.byte	0x14
	.ascii	"CHARACTER_AIAS\000"

	.byte	0x51
	.byte	0x14
	.ascii	"CHARACTER_CARLYLE\000"

	.byte	0x52
	.byte	0x14
	.ascii	"CHARACTER_CAELLACH\000"

	.byte	0x53
	.byte	0x14
	.ascii	"CHARACTER_PABLO_2\000"

	.byte	0x54
	.byte	0x14
	.ascii	"CHARACTER_GORGON_CHUnk\000"

	.byte	0x56
	.byte	0x14
	.ascii	"CHARACTER_RIEV\000"

	.byte	0x57
	.byte	0x14
	.ascii	"CHARACTER_GHEB\000"

	.byte	0x5a
	.byte	0x14
	.ascii	"CHARACTER_BERAN\000"

	.byte	0x5b
	.byte	0x14
	.ascii	"CHARACTER_CYCLOPS_CHUnk\000"

	.byte	0x5c
	.byte	0x14
	.ascii	"CHARACTER_WIGHT_CHUnk\000"

	.byte	0x5d
	.byte	0x14
	.ascii	"CHARACTER_DEATHGOYLE_CHUnk\000"

	.byte	0x5e
	.byte	0x14
	.ascii	"CHARACTER_BANDIT_CH5\000"

	.byte	0x66
	.byte	0x14
	.ascii	"CHARACTER_ONEILL\000"

	.byte	0x68
	.byte	0x14
	.ascii	"CHARACTER_GLEN\000"

	.byte	0x69
	.byte	0x14
	.ascii	"CHARACTER_ZONTA\000"

	.byte	0x6a
	.byte	0x14
	.ascii	"CHARACTER_VIGARDE\000"

	.byte	0x6b
	.byte	0x14
	.ascii	"CHARACTER_LYON_FINAL\000"

	.byte	0x6c
	.byte	0x14
	.ascii	"CHARACTER_ORSON\000"

	.byte	0x6d
	.byte	0x14
	.ascii	"CHARACTER_SOLDIER_83\000"

	.byte	0x83
	.byte	0x14
	.ascii	"CHARACTER_MONSTER_BA\000"

	.byte	0xba
	.byte	0x14
	.ascii	"CHARACTER_FOMORTIIS\000"

	.byte	0xbe
	.byte	0x14
	.ascii	"CHARACHER_FRELIAN\000"

	.byte	0xc0
	.byte	0x14
	.ascii	"CHARACTER_FADO\000"

	.byte	0xc5
	.byte	0x14
	.ascii	"CHARACTER_HAYDEN\000"

	.byte	0xc7
	.byte	0x14
	.ascii	"CHARACTER_MANSEL\000"

	.byte	0xc8
	.byte	0x14
	.ascii	"CHARACTER_KLIMT\000"

	.byte	0xc9
	.byte	0x14
	.ascii	"CHARACTER_DARA\000"

	.byte	0xca
	.byte	0x14
	.ascii	"CHARACTER_ISMAIRE\000"

	.byte	0xcb
	.byte	0x14
	.ascii	"CHARACTER_MESSENGER\000"

	.byte	0xcc
	.byte	0x14
	.ascii	"CHARACTER_CITIZEN\000"

	.byte	0xfc
	.byte	0x14
	.ascii	"CHARACTER_ARENA_OPPONENT\000"

	.byte	0xfd
	.byte	0x14
	.ascii	"CHARACTER_WALL\000"

	.byte	0xfe
	.byte	0x14
	.ascii	"CHARACTER_SNAG\000"

	.byte	0xff
	.byte	0x0
	.byte	0x1a
	.4byte	0x3905
	.ascii	"event_autoload_pid_idx\000"

	.byte	0x4
	.byte	0xd
	.byte	0x73
	.byte	0x14
	.ascii	"CHARACTER_EVT_LEADER\000"

	.byte	0x0
	.byte	0x1b
	.ascii	"CHARACTER_EVT_ACTIVE\000"

	.4byte	0xffffffff
	.byte	0x1b
	.ascii	"CHARACTER_EVT_SLOTB\000"

	.4byte	0xfffffffe
	.byte	0x1b
	.ascii	"CHARACTER_EVT_SLOT2\000"

	.4byte	0xfffffffd
	.byte	0x0
	.byte	0x4
	.4byte	0x3947
	.ascii	"DebugPInfo\000"

	.byte	0xc
	.byte	0xe
	.byte	0x4
	.byte	0x5
	.ascii	"idx\000"

	.byte	0xe
	.byte	0x5
	.4byte	0x82
	.byte	0x2
	.byte	0x23
	.byte	0x0
	.byte	0x5
	.ascii	"pname\000"

	.byte	0xe
	.byte	0x6
	.4byte	0x415
	.byte	0x2
	.byte	0x23
	.byte	0x4
	.byte	0x5
	.ascii	"jname\000"

	.byte	0xe
	.byte	0x7
	.4byte	0x415
	.byte	0x2
	.byte	0x23
	.byte	0x8
	.byte	0x0
	.byte	0xb
	.4byte	0x3953
	.4byte	0x3905
	.byte	0xc
	.byte	0xff
	.byte	0x0
	.byte	0x21
	.ascii	"gDebugPInfo\000"

	.byte	0xe
	.byte	0xa
	.4byte	0x3947
	.byte	0x1
	.byte	0x5
	.byte	0x3
	.4byte	gDebugPInfo
	.byte	0x0

	.section	.debug_pubnames
	.4byte	0x1e
	.2byte	0x2
	.4byte	.debug_info
	.4byte	0x396e
	.4byte	0x3953
	.ascii	"gDebugPInfo\000"

	.4byte	0x0
.ALIGN 2, 0
